In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/transactions.csv')

In [50]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6849346 entries, 0 to 6849345
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   tr_datetime  object
 2   mcc_code     int64
 3   tr_type      int64
 4   amount       float64
 5   term_id      object
dtypes: float64(1), int64(3), object(2)
memory usage: 313.5+ MB

In [58]:
null_term_id_num = sum(df['term_id'].isna())

null_term_id_num / len(df)

0.40371664681562297

In [54]:
df['term_id'].isna().any()

True

In [43]:
df = pd.read_parquet('data/client_id_map.parquet')

In [45]:
df.head()

  customer_id  encoded_client_id
0    10003267                  0
1    10004871                  1
2    10005741                  2
3    10011328                  3
4    10014090                  4

In [46]:
len(df)

15000

In [44]:
set(df['encoded_client_id']) - set(range(len(df)))

set()

In [38]:
set(df['encoded_client_id'])

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...}

In [39]:
print(df['customer_id'])

0        10003267
1        10004871
2        10005741
3        10011328
4        10014090
           ...
14995    99985917
14996    99988578
14997    99991245
14998      999976
14999    99999680
Name: customer_id, Length: 15000, dtype: object

In [40]:
for i in range(len(df)):
    print(df['customer_id'][i], df['encoded_client_id'][i])

10003267 0
10004871 1
10005741 2
10011328 3
10014090 4
10018695 5
10023080 6
10026296 7
10034284 8
1004170 9
10045498 10
10055880 11
10056437 12
10058557 13
10058778 14
10063530 15
10064386 16
10066310 17
10067396 18
10071732 19
10078312 20
10094853 21
10110730 22
10126330 23
1013552 24
1013842 25
1013875 26
10159490 27
10166707 28
10171705 29
10176170 30
10179649 31
1018926 32
10206133 33
1020634 34
10229977 35
10230827 36
1023983 37
10246339 38
10252148 39
10257726 40
10259614 41
10269885 42
10280886 43
10290561 44
1029705 45
10303548 46
10304262 47
10309206 48
10324267 49
10328342 50
10331386 51
10334951 52
10344936 53
10353051 54
10364899 55
10373501 56
10376120 57
10376412 58
10377190 59
10384721 60
10385103 61
10403039 62
104032 63
10403659 64
10413542 65
1044883 66
10464121 67
10467007 68
10469400 69
10476857 70
10482140 71
10490454 72
10493682 73
10499284 74
10506836 75
10519292 76
10521111 77
10524021 78
10565884 79
10574425 80
10589831 81
10596896 82
10598219 83
10600725 84
10600843 85
10607076 86
10645422 87
10646582 88
10651006 89
10656890 90
10657243 91
1066224 92
10666447 93
10678387 94
10681267 95
10682079 96
10685683 97
10690962 98
10693331 99
10696706 100
10702887 101
10711025 102
1071870 103
10720023 104
10720945 105
10722119 106
10727511 107
10747474 108
10748004 109
10758984 110
10759723 111
10763919 112
10767925 113
10774706 114
10789064 115
10794338 116
10796448 117
10802212 118
10802856 119
10805399 120
10810592 121
10812965 122
10814222 123
10818467 124
1081993 125
10831740 126
10832516 127
10835381 128
10839610 129
10845911 130
10867310 131
10875817 132
1087616 133
10877395 134
1088175 135
10886531 136
10888907 137
10890438 138
10895224 139
10909988 140
10915793 141
10928546 142
10930506 143
1093304 144
1094663 145
10954763 146
1096220 147
10966995 148
10967870 149
1099483 150
11007795 151
11032699 152
11039185 153
11056834 154
11060478 155
11062726 156
11065148 157
11071792 158
11073241 159
11077329 160
11080771 161
11089937 162
1109129 163
11092914 164
11094849 165
11107679 166
11109587 167
11114169 168
11122702 169
11123573 170
11139526 171
11142729 172
11142969 173
11143956 174
11148023 175
1115426 176
11167057 177
11173473 178
11175443 179
11186103 180
11195829 181
11203768 182
11204688 183
11218538 184
11222990 185
11224986 186
1122742 187
11227474 188
11228581 189
11234608 190
11249127 191
11254893 192
11259870 193
11267999 194
11279612 195
11281442 196
11288915 197
11291751 198
11292128 199
11294007 200
11316922 201
11321790 202
11325341 203
11327023 204
11330604 205
11332993 206
1133595 207
11337455 208
11341232 209
11349383 210
11353867 211
11356541 212
11356888 213
11358754 214
1136140 215
11365859 216
11370413 217
11373512 218
11376556 219
11377460 220
11381668 221
1139307 222
11397041 223
11397076 224
11403503 225
11416905 226
11419740 227
11421609 228
11425537 229
11434701 230
114348 231
11446286 232
11447347 233
11449729 234
11449765 235
11455048 236
11460051 237
11463393 238
11468930 239
11469033 240
11474181 241
11476779 242
11479064 243
11511328 244
11528415 245
11529524 246
11532626 247
11533763 248
11535483 249
11542491 250
115617 251
11561813 252
11562634 253
11573006 254
11576272 255
11576588 256
1157982 257
11585045 258
11596802 259
11604095 260
11613882 261
11621687 262
11624643 263
11625700 264
11627221 265
11627763 266
11631304 267
11631584 268
11631823 269
11637315 270
11639778 271
11653939 272
11661664 273
11661930 274
11671863 275
11677380 276
11681378 277
11691762 278
11701078 279
11702148 280
11703306 281
11724036 282
11734416 283
11738678 284
11739616 285
117556 286
11763909 287
11765794 288
1177740 289
11777784 290
1177962 291
11819055 292
11819140 293
11822388 294
11831433 295
11835383 296
11840983 297
11841860 298
11842227 299
11851829 300
11865703 301
11882317 302
11898035 303
11925955 304
11931236 305
11931380 306
11935430 307
11946025 308
11947576 309
11963965 310
11967399 311
11971296 312
11983092 313
11994958 314
12001537 315
12010535 316
12019706 317
12022974 318
12036459 319
12041525 320
12042186 321
12044720 322
12051455 323
12053904 324
12056620 325
12058501 326
12059762 327
12064455 328
12067626 329
12069120 330
12070067 331
12070296 332
12071388 333
12075801 334
12095671 335
12095826 336
12096448 337
1210592 338
1211346 339
12116728 340
12120260 341
12139199 342
12149925 343
12175094 344
1217764 345
12178012 346
12187862 347
12193461 348
12234095 349
12235801 350
12236336 351
12239681 352
12241429 353
12252020 354
12254881 355
12258138 356
12261215 357
12269528 358
12273634 359
12279093 360
12280482 361
12281103 362
12282192 363
12284205 364
12284486 365
12289409 366
1230741 367
12307571 368
12325802 369
12336680 370
12338797 371
12342280 372
12374003 373
1238197 374
12390619 375
12403092 376
12406425 377
12434084 378
12437618 379
12448845 380
12450114 381
12467102 382
12468790 383
12494146 384
12500141 385
12509777 386
12510907 387
12511084 388
12520991 389
12526703 390
12528382 391
12542015 392
12542657 393
12547172 394
12547506 395
12548009 396
12548616 397
12564682 398
1256938 399
12570806 400
12591110 401
12596291 402
12598453 403
126081 404
12610287 405
12611230 406
12614648 407
12615543 408
12617567 409
12630779 410
1263601 411
12646472 412
12652859 413
12660882 414
12678319 415
12678722 416
12680585 417
126935 418
12697071 419
12697220 420
12697882 421
12701940 422
12707826 423
12710845 424
12711646 425
1271467 426
12720003 427
12721595 428
12725274 429
12728902 430
12730223 431
12739123 432
12746283 433
12746284 434
12749531 435
12773836 436
12781840 437
12785195 438
12794352 439
127946 440
12803072 441
12811046 442
12822386 443
12824902 444
12826852 445
12829225 446
12833442 447
12842184 448
12854702 449
12856049 450
12878356 451
12889098 452
1289086 453
12896717 454
12908885 455
12908901 456
12911069 457
12914046 458
12914769 459
1291480 460
12925117 461
12931945 462
12932872 463
12942642 464
12965529 465
12976812 466
1297829 467
12981242 468
1298146 469
12981808 470
12987697 471
12995896 472
12997681 473
13003554 474
13004560 475
13011786 476
13025490 477
13026435 478
13028904 479
13032345 480
13034121 481
13054202 482
13067380 483
13077345 484
1308272 485
13083218 486
1310584 487
13126579 488
13128717 489
1316496 490
13170353 491
13179575 492
13182172 493
13186622 494
13191753 495
13195994 496
13204747 497
13210353 498
13221041 499
1322942 500
13234632 501
13241753 502
13245340 503
13246133 504
13260220 505
13267878 506
13292327 507
13302287 508
13316918 509
13318961 510
13324952 511
13325805 512
13333685 513
13358704 514
13360298 515
13360507 516
1336622 517
13379653 518
1338875 519
13388782 520
13389616 521
13398107 522
13404665 523
1340586 524
13418393 525
13419115 526
13422446 527
13422613 528
13431113 529
13431883 530
13440692 531
13447213 532
13451353 533
13451465 534
13466200 535
13475789 536
13476395 537
13491189 538
13498047 539
13520040 540
13528851 541
13529871 542
13532732 543
13552331 544
13554236 545
13568964 546
13572234 547
13575882 548
13584143 549
13584223 550
13587967 551
13590968 552
13595171 553
13602205 554
13604102 555
13605073 556
1361341 557
1361923 558
13620003 559
13632967 560
13637343 561
13637870 562
13641759 563
13642050 564
13645274 565
13659037 566
13664173 567
13670238 568
13670767 569
13672389 570
13682748 571
13695605 572
13704599 573
13705197 574
1370532 575
13712785 576
13720727 577
13724038 578
13734049 579
137367 580
13746011 581
13748035 582
13751660 583
13756442 584
13766028 585
1377061 586
13771461 587
13772117 588
13775509 589
13777610 590
13786701 591
13791482 592
13799180 593
1380455 594
13822007 595
13825301 596
13826611 597
13828654 598
13833761 599
13841185 600
13842267 601
13847189 602
13857434 603
13863600 604
1386526 605
13868306 606
13871004 607
13872241 608
13879262 609
13883186 610
13885997 611
13888373 612
13888852 613
13888991 614
13889184 615
1389092 616
13893103 617
13900192 618
13902815 619
13910371 620
13935326 621
1394168 622
13963532 623
13990747 624
14001176 625
14005433 626
14016145 627
14017807 628
14025913 629
14027711 630
14029441 631
14030201 632
14036897 633
14040287 634
14076810 635
14077395 636
14092000 637
14100143 638
14101528 639
14104664 640
14104717 641
14106416 642
14114778 643
14123285 644
14123690 645
14124897 646
14128185 647
14129852 648
14132470 649
14134377 650
14143258 651
14151691 652
14154056 653
14154413 654
14158276 655
14166485 656
14169381 657
14177005 658
14178332 659
14180180 660
14189626 661
14191306 662
14196903 663
1420045 664
1420268 665
14205771 666
14209820 667
14212610 668
14219972 669
14221391 670
14222226 671
14230443 672
14231524 673
14238559 674
14246947 675
14248648 676
14252692 677
14257147 678
14260146 679
14264900 680
14267405 681
14275743 682
14299428 683
14300407 684
14301268 685
14307675 686
14330113 687
14331004 688
14332733 689
14349913 690
14353260 691
14360608 692
14361176 693
14362107 694
14366449 695
14380708 696
14382698 697
14392168 698
14396005 699
14401707 700
14404397 701
14409598 702
14421509 703
14444565 704
14454081 705
14454241 706
14466652 707
14474509 708
14476637 709
14480573 710
14481189 711
14481681 712
14490414 713
14496242 714
14505893 715
1451776 716
1451952 717
14525059 718
14544715 719
14548818 720
14551898 721
14552261 722
14556762 723
14564793 724
14571241 725
14572195 726
14587386 727
14587736 728
14593180 729
14596151 730
14602021 731
1461541 732
14630687 733
14641163 734
14647979 735
14651755 736
14652271 737
14652932 738
14656498 739
14664253 740
14672721 741
14682884 742
1469034 743
1469056 744
14690847 745
14694355 746
14709673 747
14711088 748
14713603 749
14719845 750
14720054 751
14736748 752
14737664 753
14739087 754
14747265 755
14771683 756
14786519 757
14808847 758
14818582 759
14821988 760
14826116 761
14835466 762
14837954 763
14848931 764
14850892 765
14865801 766
14866430 767
14872527 768
14875577 769
14887515 770
14892960 771
14894393 772
14898358 773
14905888 774
14907076 775
14918729 776
14930512 777
14937933 778
14939820 779
14945938 780
14953743 781
14969345 782
14974851 783
14976384 784
14980520 785
14984900 786
14988970 787
14990644 788
15004238 789
15031489 790
15033734 791
15039371 792
15040528 793
15042079 794
15042083 795
15042508 796
15044221 797
15047873 798
1505158 799
15053840 800
15057364 801
15058566 802
1508066 803
15088828 804
1510234 805
15103892 806
15104152 807
15112348 808
15115077 809
15121468 810
1513266 811
15142137 812
15150934 813
15158844 814
15160419 815
15166647 816
15173207 817
15196059 818
15197816 819
15205815 820
15206009 821
15206594 822
15208319 823
1521146 824
15218842 825
15223800 826
15223932 827
15230899 828
15233857 829
15250320 830
15253284 831
15254530 832
15254951 833
15267436 834
15282992 835
15283573 836
15307012 837
15321146 838
15325309 839
15341897 840
15347446 841
15354016 842
15377876 843
15381290 844
15384947 845
15386233 846
15387560 847
15392798 848
15400383 849
15404394 850
15407862 851
1541259 852
15413183 853
15428955 854
15435442 855
15436657 856
15441779 857
15444986 858
15455653 859
15458619 860
15461417 861
15462118 862
1546466 863
15471394 864
15474511 865
15476291 866
15492735 867
15496197 868
15503089 869
15510666 870
15511971 871
15515571 872
15523078 873
15528235 874
15528477 875
15531589 876
15548583 877
15555810 878
15569246 879
15570959 880
15577036 881
15577985 882
15584488 883
15588952 884
15590380 885
15592985 886
15597795 887
15598730 888
15600058 889
15604721 890
15611978 891
15615770 892
1562005 893
15621022 894
15621179 895
15626188 896
15626531 897
15627664 898
1563913 899
15652973 900
15659879 901
1567274 902
1567291 903
15673882 904
1567497 905
15678379 906
15683076 907
15685502 908
1568833 909
15701539 910
1571169 911
15729290 912
15737383 913
15742901 914
15747982 915
1575030 916
15752946 917
15762885 918
15767586 919
15768193 920
15786927 921
15789572 922
15791788 923
1579633 924
15796340 925
15803958 926
15809747 927
15826213 928
1582976 929
15836028 930
15836839 931
15841147 932
15847149 933
15847268 934
1585299 935
15854896 936
15856748 937
15864413 938
15866910 939
15867759 940
15881446 941
15894791 942
15898915 943
15904515 944
15913937 945
15923301 946
15926326 947
15926722 948
1593734 949
15939752 950
15944492 951
15945483 952
15955193 953
15956854 954
15964289 955
15965494 956
15971667 957
15975329 958
15982939 959
15993282 960
16004843 961
1600833 962
16008976 963
16015698 964
16026721 965
16044366 966
16048969 967
16049334 968
16057697 969
16065892 970
16080835 971
16080959 972
16083891 973
16089461 974
16102335 975
1610310 976
16115351 977
16143064 978
16144253 979
16144518 980
16152597 981
16167490 982
16181139 983
16191966 984
16197496 985
16198741 986
16203811 987
16205321 988
16213543 989
16214146 990
1622018 991
16224951 992
16226085 993
16233088 994
16240272 995
16253417 996
1626561 997
16267765 998
16273685 999
16274002 1000
16295869 1001
16309666 1002
16321752 1003
16330781 1004
16331369 1005
16342382 1006
16351435 1007
16359236 1008
16367483 1009
16367800 1010
16371796 1011
16378266 1012
16381650 1013
16387172 1014
16392564 1015
16393345 1016
16395398 1017
16395910 1018
16404236 1019
16405988 1020
16410393 1021
16412935 1022
16419087 1023
16419166 1024
16420571 1025
16422350 1026
1643831 1027
16442855 1028
16447728 1029
16448797 1030
1645333 1031
16454787 1032
16462973 1033
16480850 1034
16481372 1035
16493417 1036
16505024 1037
16509297 1038
16522855 1039
16527738 1040
16536678 1041
16538259 1042
16542264 1043
16542862 1044
16563089 1045
16563768 1046
16568750 1047
16575331 1048
16576146 1049
16579578 1050
16585493 1051
1658650 1052
16587646 1053
16588270 1054
16591133 1055
16594215 1056
16604678 1057
16617058 1058
16617908 1059
16622470 1060
16631698 1061
16634239 1062
16662809 1063
16671175 1064
16671263 1065
16689751 1066
16692763 1067
16697632 1068
16704747 1069
16711781 1070
16730077 1071
16731650 1072
16744894 1073
16745107 1074
16745983 1075
16749393 1076
16751713 1077
16753848 1078
16761497 1079
16764721 1080
16767160 1081
16768663 1082
16771902 1083
16779630 1084
16795304 1085
16799312 1086
16804239 1087
16806190 1088
16810200 1089
16826344 1090
16835324 1091
16840276 1092
16843415 1093
16848662 1094
16862454 1095
16867721 1096
168767 1097
16893207 1098
16903491 1099
16905276 1100
16910920 1101
16917381 1102
16918320 1103
1691972 1104
16920927 1105
16923362 1106
1692635 1107
16936202 1108
16938566 1109
16939122 1110
16949486 1111
16958651 1112
16967590 1113
16977754 1114
16981134 1115
16984655 1116
16989126 1117
16989493 1118
16989800 1119
1699717 1120
17005865 1121
1701585 1122
1702393 1123
17027775 1124
17031888 1125
17033704 1126
17035523 1127
17038281 1128
17039869 1129
17041637 1130
17044298 1131
17045471 1132
1704698 1133
17060000 1134
17073428 1135
17075581 1136
17081083 1137
17090426 1138
1709422 1139
17095064 1140
17096335 1141
17096973 1142
17106100 1143
17113299 1144
17118781 1145
17120363 1146
17120770 1147
17130516 1148
1713682 1149
1714555 1150
1716098 1151
17166860 1152
17168015 1153
17171316 1154
17171343 1155
17173846 1156
17178672 1157
17181384 1158
17188865 1159
17194012 1160
17208030 1161
17216285 1162
17217359 1163
17217421 1164
17232316 1165
172390 1166
17241534 1167
17256393 1168
17260193 1169
17266117 1170
17275036 1171
17281851 1172
17285865 1173
17287341 1174
17292612 1175
17293191 1176
17299088 1177
17302287 1178
17304472 1179
17306217 1180
17319846 1181
17326412 1182
17327321 1183
1732939 1184
17331961 1185
17340837 1186
17346481 1187
17350935 1188
17352837 1189
17360599 1190
17361562 1191
17384779 1192
17389182 1193
17392669 1194
17394948 1195
17396832 1196
17398749 1197
17403698 1198
17422997 1199
17427240 1200
17431962 1201
17433826 1202
17437813 1203
17440302 1204
17441830 1205
17443767 1206
174467 1207
17447144 1208
17456490 1209
1745827 1210
17459382 1211
1747033 1212
17471011 1213
17471274 1214
1747627 1215
1748625 1216
17487230 1217
17502871 1218
17515894 1219
17518271 1220
17537261 1221
17543160 1222
17574120 1223
17576256 1224
17580250 1225
17589274 1226
17596405 1227
17605074 1228
17610658 1229
17634947 1230
17637161 1231
17637572 1232
1764918 1233
17659964 1234
17661325 1235
17662250 1236
17670150 1237
17674010 1238
17685580 1239
17695034 1240
17698452 1241
17698586 1242
17703557 1243
17703907 1244
177299 1245
17732156 1246
17732747 1247
17737985 1248
17750079 1249
17755070 1250
17757519 1251
17761745 1252
17770789 1253
17774807 1254
17793655 1255
17797588 1256
17831625 1257
17832283 1258
17850899 1259
17859769 1260
17861663 1261
17862099 1262
17875998 1263
17880257 1264
17880287 1265
17880785 1266
17887190 1267
17888939 1268
17889916 1269
17891979 1270
17899884 1271
17904208 1272
17908138 1273
17913186 1274
17914429 1275
17915071 1276
17923253 1277
17929375 1278
17941785 1279
17958840 1280
17979664 1281
1798485 1282
17992634 1283
17995188 1284
18000572 1285
18004471 1286
18019658 1287
18020299 1288
18022583 1289
18029928 1290
18032393 1291
18040048 1292
1804650 1293
18048133 1294
18053122 1295
18059478 1296
18072028 1297
18073912 1298
18074104 1299
18087645 1300
1810386 1301
18104975 1302
18123320 1303
18126138 1304
18139443 1305
18152172 1306
18152888 1307
18155281 1308
18157127 1309
18164843 1310
18177248 1311
18201273 1312
18211024 1313
18213223 1314
18213962 1315
18230930 1316
18232705 1317
18235022 1318
18256987 1319
1826000 1320
18260853 1321
18263937 1322
18265734 1323
1828229 1324
18291913 1325
18293426 1326
18314837 1327
18319720 1328
18321497 1329
18331794 1330
18333711 1331
18344091 1332
18345402 1333
18347957 1334
18348644 1335
18350404 1336
18351390 1337
18358597 1338
18360110 1339
18366978 1340
18389379 1341
18399534 1342
18418576 1343
18429765 1344
18432893 1345
1843439 1346
1844176 1347
18450058 1348
18451037 1349
18454528 1350
1846496 1351
18470346 1352
18474311 1353
18480529 1354
18488176 1355
1848866 1356
18490455 1357
18501672 1358
18501812 1359
18504401 1360
18506768 1361
1851193 1362
18516500 1363
18523734 1364
18527429 1365
18528564 1366
18550241 1367
18550989 1368
18552071 1369
18562357 1370
18568009 1371
18571719 1372
18586518 1373
18590160 1374
18597595 1375
18598288 1376
1859939 1377
18609856 1378
18627936 1379
18628974 1380
18629075 1381
18630831 1382
18630870 1383
18640023 1384
18642891 1385
18646751 1386
18649620 1387
18653633 1388
18654396 1389
18670012 1390
18671863 1391
186730 1392
1867994 1393
18686042 1394
18690123 1395
18694042 1396
18699655 1397
18711616 1398
18718602 1399
18727270 1400
18734965 1401
18746693 1402
18753299 1403
18762843 1404
1877761 1405
1877899 1406
18780719 1407
18784555 1408
18789683 1409
18798580 1410
18806555 1411
18812819 1412
18816938 1413
18824201 1414
18825101 1415
18828201 1416
18836944 1417
18864557 1418
18870871 1419
18872798 1420
1887297 1421
18877330 1422
18879570 1423
18880490 1424
1888728 1425
18889791 1426
18894090 1427
18894701 1428
18903746 1429
18904103 1430
18911055 1431
18912624 1432
18915069 1433
18915256 1434
18925330 1435
189257 1436
18932060 1437
18935419 1438
18935754 1439
18935779 1440
18938727 1441
1893992 1442
18948724 1443
18962492 1444
18965515 1445
18967006 1446
18967458 1447
18977893 1448
18979312 1449
18982540 1450
18992359 1451
19006787 1452
19011675 1453
19018635 1454
19030022 1455
19031983 1456
19061005 1457
19084264 1458
19087930 1459
19100322 1460
19101727 1461
19110007 1462
19140098 1463
19143789 1464
1914718 1465
19149664 1466
19153043 1467
19158728 1468
19164890 1469
19170445 1470
19174877 1471
19186106 1472
19195790 1473
19196586 1474
19205707 1475
19217936 1476
19218689 1477
19231543 1478
19235833 1479
19237958 1480
19239257 1481
1925153 1482
19259366 1483
19261311 1484
19262133 1485
19270512 1486
19282591 1487
19282673 1488
19283529 1489
19287737 1490
19295298 1491
1929883 1492
19309710 1493
19309943 1494
19327580 1495
19330058 1496
19345776 1497
19350485 1498
1936060 1499
19368278 1500
19375709 1501
19380379 1502
19380743 1503
19382701 1504
19383241 1505
19404141 1506
19409011 1507
19410362 1508
19411412 1509
19415800 1510
19423861 1511
19425991 1512
1943360 1513
19438089 1514
19439865 1515
19443014 1516
19455514 1517

In [36]:
train_trx_df = pd.read_parquet('data/train_trx.parquet')

In [37]:
train_trx_df.head()

,customer_id,event_time,amount,mcc_code,tr_type,term_id,trx_count,target,encoded_client_id
0,10058778,"[23.35869212962963, 23.359502314814815, 36.498...","[13.420652589715486, -13.420652589715486, 14.6...","[2, 6, 3, 2, 2, 3, 2, 3, 2, 6, 6, 3, 10, 3, 2,...","[8, 13, 6, 3, 3, 23, 3, 11, 8, 19, 20, 6, 2, 6...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",142,1.0,14
1,10230827,"[0.25885416666666666, 1.5346412037037038, 1.65...","[13.015188216272872, -10.01949835204266, -9.76...","[3, 2, 5, 8, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 3, ...","[29, 3, 5, 5, 3, 3, 3, 4, 3, 3, 4, 3, 3, 4, 29...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",279,0.0,36
2,11681378,"[0.3015393518518519, 0.3589583333333333, 0.875...","[-8.41023807171957, -7.9242460340479255, -9.91...","[4, 7, 2, 2, 11, 5, 7, 6, 2, 7, 7, 3, 6, 7, 7,...","[4, 2, 27, 28, 2, 5, 2, 13, 3, 2, 2, 9, 13, 2,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",881,1.0,277
3,14123285,"[15.489155092592593, 21.68777777777778, 23.612...","[12.792045221523114, 12.216683253401992, -10.7...","[3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, ...","[11, 9, 16, 25, 25, 16, 11, 6, 16, 25, 11, 17,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",1051,0.0,644
4,16536678,"[75.40552083333333, 75.59731481481481, 83.5602...","[14.336942434053569, -9.326395693771916, -9.32...","[2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, ...","[8, 4, 4, 4, 4, 8, 4, 4, 4, 8, 4, 4, 4, 4, 4, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",128,0.0,1041

In [43]:
train__coles_item_ids = {el for seq in train_trx_df['mcc_code'] for el in seq}

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185}

In [44]:
train__coles_item_ids == set(range(2, 186))

True

In [45]:
test_trx_df = pd.read_parquet('data/test_trx.parquet')
test_trx_df.head()

,customer_id,event_time,amount,mcc_code,tr_type,term_id,trx_count,target,encoded_client_id
0,24227698,"[2.6528125, 7.377939814814815, 16.875011574074...","[-10.424948618947251, -11.811220643640558, -11...","[2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, ...","[3, 3, 3, 3, 8, 3, 4, 8, 3, 3, 8, 3, 3, 8, 8, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",235,1,2293
1,29097966,"[-0.125, 0.2008449074074074, 1.875, 1.875, 3.2...","[-8.79882449483086, -7.024613442631785, -9.204...","[8, 4, 8, 5, 4, 2, 8, 9, 2, 4, 4, 8, 26, 2, 5,...","[5, 4, 5, 5, 4, 3, 5, 5, 3, 4, 4, 5, 2, 3, 2, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",1255,1,3110
2,46431440,"[12.289259259259259, 14.403055555555556, 14.45...","[10.974982295004144, -12.227733055882192, -8.4...","[2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2, ...","[8, 3, 18, 3, 4, 3, 8, 4, 3, 4, 18, 3, 4, 3, 1...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",144,0,5946
3,48119333,"[0.875, 1.116886574074074, 1.4504398148148148,...","[-8.969759419013014, 11.118080809668006, 11.62...","[49, 3, 3, 2, 8, 3, 4, 8, 8, 76, 5, 4, 4, 4, 5...","[10, 6, 9, 16, 5, 6, 4, 5, 5, 5, 5, 4, 4, 4, 5...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",632,1,6233
4,50796712,"[1.0409143518518518, 1.2863194444444446, 1.293...","[-10.722058283317635, -7.773670190197818, -9.3...","[8, 5, 5, 5, 2, 5, 9, 5, 4, 5, 5, 4, 5, 5, 5, ...","[5, 2, 5, 2, 3, 5, 5, 5, 4, 5, 5, 4, 5, 5, 5, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",455,1,6710

In [47]:
test__coles_item_ids = {el for seq in test_trx_df['mcc_code'] for el in seq}

In [49]:
test__coles_item_ids == train__coles_item_ids

False

In [55]:
# <= is a `is_subset` operator
test__coles_item_ids <= train__coles_item_ids

True

In [46]:
test_trx_df['encoded_client_id'].unique()

array([ 2293,  3110,  5946,  6233,  6710,  8867,  9877, 10575, 13190,
       13802, 14110,   184,  1552,  1952,  2745,  2865,  3153,  4574,
        6555,  8891,  9712, 11250, 11770, 12554,   595,  3868,  4703,
        5250,  6825,  7888,  8111, 10597, 10813, 10906, 11000, 12639,
       12968, 13238, 13726,   613,  3677,  3712,  4349,  5399,  7747,
        9939, 10831,   351,   751,  2433,  2815,  2948,  3731,  4085,
        4779,  5165,  6049,  6101,  6192,  6681,  7712,  9586,  9695,
       11484, 11919, 12309, 12484, 13005, 13461, 13681,   833,  3956,
        4541,  4616,  7956,  8719,  9708, 11007, 11057, 13260,  3055,
        3760,  3830,  5136,  9729, 12412, 13476, 14886,   592,   992,
        1066,  2793,  2894,  4398,  6299,  9802, 10492, 10818, 13710,
        1785,  2522,  2867,  3563,  4232,  4483,  5438,  6119,  6169,
        6276,  7475,  8055,  8130,  8412,  8429, 13932,   811,  2749,
        2770,  3345,  3642,  5154,  6376,  6934,  6970,  7379,  7926,
        8275, 10564, 12433, 13627, 13776, 14611, 14865,   433,   873,
        1870,  3124,  4419,  5718,  5939,  8098,  9669, 10355, 10948,
       11247, 13720, 14456,    82,  1556,  1784,  3505,  3926,  6769,
       11301, 13317, 14569,  2357,  2914,  3023,  3653,  4128,  5872,
        8745,  9813,  9830, 11756, 12410, 14245, 14907, 14983,   713,
        1385,  2049,  2187,  2588,  4212,  5964,  5985,  6092,  6894,
        7019,  7693,  9787, 10534, 13481,   576,  4877,  5593,  6689,
        6937,  7279,  8525,  8682,  9233, 10365,   641,  1835,  1862,
        1883,  2658,  3276,  3616,  4141,  5038,  7090,  9897,  9927,
       10215, 11644, 11813, 12790, 12910,   732,  1698,  2329,  3885,
        4029,  4455,  6285,  7824,  9486, 10746, 11219, 12504, 12879,
       13298, 13617, 14766,  1351,  1363,  1980,  2193,  4557,  5077,
        6187,  6600,  6983,  7825,  8494,  8828,  9293, 11841, 11893,
       12951, 14327, 14902, 14957,   924,  1516,  2331,  3169,  4162,
        5616,  7576,  7769,  9023, 10991, 12892, 13006,  3326,  3332,
        4659,  4694,  7051,  9772, 10594, 10922, 11304, 11606, 14220,
        1210,  2302,  3259,  3558,  3796,  4190,  6806,  8178,  9121,
       12236,    32,   578,   815,   837,  3435,  4672,  4932,  7538,
        7764,  9682, 10843, 13596, 14892,   915,  3318,  3403,  4062,
        4218,  5131,  7220,  8028,  8557,  9092, 10925, 11773, 12867,
       13871, 14145,  1694,  3889,  4700,  6497,  8327, 11720, 12334,
       13510, 14051,   143,   591,  1019,  1572,  2444,  4790,  6742,
        7930,  8089,  9156, 10074, 11397, 13280, 13299,  1378,  2843,
        3158,  4621,  6453,  7860,  7960,  8128,  9481,  9597, 10203,
       10422, 11183, 13075, 14893,   981,  1110,  1460,  1675,  3383,
        4098,  4407,  4503,  6259,  6813,  7119,  7997,  9514, 12193,
       12645, 13170,  2284,  2587,  3246,  8469,  8558, 10221, 12622,
       14698,  1691,  2351,  2947,  4734,  4955,  5856,  6985,  7138,
        8249,  8992, 11043, 11059, 11126, 12255, 12837,   138,  1063,
        1251,  2758,  2878,  4129,  4890,  9028,  9637, 11159, 11715,
       12237, 13957, 14436, 14942,  1137,  2186,  2400,  4819,  7632,
        7818,  9240, 10677, 11997, 12903, 13079, 13098, 14287, 14980,
        1931,  3529,  4036,  4497,  6677,  7848, 11018, 11146, 11468,
       12509, 13588, 13702,   537,   895,  1007,  2254,  3109,  3138,
        3256,  4747,  5777,  6543, 11831, 12018,    56,   198,  1077,
        2228,  5571,  6463,  7305,  7608,  9932, 10076, 12678, 12989,
       14063, 14416,    94,   712,  3166,  4017,  5622,  8143, 11492,
       14846,  1576,  1692,  4209,  4797,  4805,  5625,  5967,  6205,
        6815,  8259,  9443,  9539, 10652, 10982, 11281, 11456, 11834,
       12618, 13179, 13242, 14795,   283,   297,   411,  1238,  2250,
        3494,  4874,  5726,  5899,  7407,  8078, 10397, 11987, 12046,
         617,  1209,  1876,  1930,  2206,  2871,  3937,  3941,  4117,
        5815,  6949,  7350,  8605,  8897, 10850, 11022, 12381, 12679,
         455,  2092,  3033,  4114,  4618,  4850,  7373,  8976,  9148,
        9252, 10567, 11348, 13054, 13103, 14862,   362,   718,  1988,
        6209,  6412,  6492,  6820,  7054,  7780,  8459,  8595,  9112,
        9295, 11058, 11296, 12462, 12556, 12921, 13165, 13795, 14572,
       14831,  2543,  2819,  3646,  4923,  9614,  9657, 12175, 12213,
       12501, 13225, 14259, 14816,   404,  6307,  7146,  9132, 10732,
       13660, 14668, 14763,   369,  1477,  2943,  3325,  5845,  6297,
        6475,  6899, 11046, 12933, 13194,   572,  1189,  1505,  2981,
        3237,  3755,  5589,  7473,  8462,  9840, 10063, 10650, 12437,
       12643, 12670, 14250, 14300,   116,  5259,  5869,  5919,  8194,
        8333,  9716, 10070, 11530, 13457,  1761,  3248,  3500,  3696,
        5032,  6319,  6501,  6929,  9347, 10602, 11320, 11678, 12311,
       12423, 13308, 13640,    87,   662,   925,  3233,  3557,  4854,
        5645,  5995,  6158,  6606,  6718,  9278,  9720, 10716, 10916,
       11087, 11551, 11730, 12266, 13688, 14653,   993,  2002,  3339,
        4366,  6472,  7904,  8144,  9409,  9800, 10399, 11714,    17,
         991,  1878,  2647,  3009,  4415,  5657,  6236,  7259,  9093,
        9850, 11959, 12248, 12746, 13487, 14651,   401,   902,  1578,
        2332,  2333,  5194,  6162,  7111,  8109,  8489,  8730,  9761,
       10175, 10573, 11074, 13089, 13793,  6210,  6423,  6433,  6686,
        6702,  7384,  9797, 10830, 12582, 13572, 14730,   281,   428,
        1872,  2087,  2388,  2912,  6410, 13202, 13486, 13879, 14036,
       14260,   848,  1284,  1951,  2352,  2689,  3766,  6176,  6721,
        7650,  7968,  8135,  8543, 10194, 10213, 11102, 11688, 14840,
        2629,  3022,  3322,  3901,  6442,  6804,  7103,  7399,  8148,
       10327, 11945, 13059, 13162, 14342,   711,  4427,  4844,  5570,
        6847,  7233,  7919,  8231,  8969,  9950, 10282, 11003, 11165,
       11413, 11443, 12778, 13188, 13587,   338,   638,  3927,  4584,
        5125,  5432,  6723,  6955,  7165,  8724,  9203,  9393,  9873,
        9949, 10121, 12226, 13650, 13769, 13888,  1181,  1965,  2610,
        4934,  5711,  5844,  6055,  7161,  8164,  8749,  9120,  9884,
       11514,    26,  1731,  2109,  3728,  3733,  3878,  3920,  5636,
        5918, 12324, 12397, 12925, 13563, 14418,     9,  2037,  3940,
        4660,  5351,  6286,  7779,  9342, 10645, 11505, 11800, 12676,
       12705, 13245, 13272,  1634,  2691,  3170,  4843,  5363,  5722,
        6405,  7438,  7901,  8002,  8409,  9775,  9976, 12079, 12371,
       12372, 13808, 14265], dtype=int32)

In [3]:
import torch

In [4]:
item_id2train_graph_id = torch.load('./data/graphs/weighted/item_id2train_graph_id.pt')

In [5]:
item_id2train_graph_id

tensor([    0,     0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167,
        14168, 14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177,
        14178, 14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187,
        14188, 14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197,
        14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207,
        14208, 14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217,
        14218, 14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227,
        14228, 14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237,
        14238, 14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247,
        14248, 14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257,
        14258, 14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267,
        14268, 14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277,
        14278, 14279, 14280, 14281, 14282, 14283, 14284, 14285, 14286, 14287,
        14288, 14289, 14290, 14291, 14292, 14293, 14294, 14295, 14296, 14297,
        14298, 14299, 14300, 14301, 14302, 14303, 14304, 14305, 14306, 14307,
        14308, 14309, 14310, 14311, 14312, 14313, 14314, 14315, 14316, 14317,
        14318, 14319, 14320, 14321, 14322, 14323, 14324, 14325, 14326, 14327,
        14328, 14329, 14330, 14331, 14332, 14333, 14334, 14335, 14336, 14337,
        14338, 14339, 14340, 14341, 14342, 14343])

In [6]:
len(item_id2train_graph_id)

186

In [7]:
item_id2train_graph_id

tensor([    0,     0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167,
        14168, 14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177,
        14178, 14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187,
        14188, 14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197,
        14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207,
        14208, 14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217,
        14218, 14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227,
        14228, 14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237,
        14238, 14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247,
        14248, 14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257,
        14258, 14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267,
        14268, 14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277,
        14278, 14279, 14280, 14281, 14282, 14283, 14284, 14285, 14286, 14287,
        14288, 14289, 14290, 14291, 14292, 14293, 14294, 14295, 14296, 14297,
        14298, 14299, 14300, 14301, 14302, 14303, 14304, 14305, 14306, 14307,
        14308, 14309, 14310, 14311, 14312, 14313, 14314, 14315, 14316, 14317,
        14318, 14319, 14320, 14321, 14322, 14323, 14324, 14325, 14326, 14327,
        14328, 14329, 14330, 14331, 14332, 14333, 14334, 14335, 14336, 14337,
        14338, 14339, 14340, 14341, 14342, 14343])

In [8]:
unique_elements = item_id2train_graph_id.unique()
unique_elements

tensor([    0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168,
        14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177, 14178,
        14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187, 14188,
        14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197, 14198,
        14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207, 14208,
        14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217, 14218,
        14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227, 14228,
        14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237, 14238,
        14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247, 14248,
        14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257, 14258,
        14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267, 14268,
        14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277, 14278,
        14279, 14280, 14281, 14282, 14283, 14284, 14285, 14286, 14287, 14288,
        14289, 14290, 14291, 14292, 14293, 14294, 14295, 14296, 14297, 14298,
        14299, 14300, 14301, 14302, 14303, 14304, 14305, 14306, 14307, 14308,
        14309, 14310, 14311, 14312, 14313, 14314, 14315, 14316, 14317, 14318,
        14319, 14320, 14321, 14322, 14323, 14324, 14325, 14326, 14327, 14328,
        14329, 14330, 14331, 14332, 14333, 14334, 14335, 14336, 14337, 14338,
        14339, 14340, 14341, 14342, 14343])

In [10]:
torch.equal(
    item_id2train_graph_id[len(item_id2train_graph_id)-len(unique_elements):],
    unique_elements
)

True

In [13]:
client_id2train_graph_id = torch.load('./data/graphs/weighted/client_id2train_graph_id.pt')

In [14]:
len(client_id2train_graph_id)

15000

In [29]:
set(map(int, client_id2train_graph_id.unique())) == set(range(14160))

True

In [10]:
item_id2full_graph_id = torch.load('./data/graphs/weighted/item_id2full_graph_id.pt')

In [11]:
len(item_id2full_graph_id)

185

In [23]:
item_id2full_graph_id

NameError: name 'item_id2full_graph_id' is not defined

In [85]:
client_id2full_graph_id = torch.load('./data/graphs/weighted/client_id2full_graph_id.pt')

In [87]:
len(client_id2full_graph_id)

15000

In [88]:
client_id2full_graph_id

tensor([    0,     1,     2,  ..., 14997, 14998, 14999])

In [89]:
client_id2full_graph_id.unique()

tensor([    0,     1,     2,  ..., 14997, 14998, 14999])

In [93]:
{int(el) for el in client_id2full_graph_id} == set(range(len(client_id2train_graph_id)))

True

In [34]:
client_id2train_graph_id[df['encoded_client_id'].unique()]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
%cd ..

/path/to/repo/Documents/my-coles-gnn-experimetns

/path/to/repo/.local/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [18]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph, ClientItemGraphFull

/path/to/repo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

ModuleNotFoundError: No module named '_lzma'

In [ ]:
graph_file_path = 'data/graphs/weighted/train_graph.bin'
client_item_graph = ClientItemGraphFull.from_graph_file(graph_file_path, 'cpu')

In [ ]:
print(client_item_graph.g.nodes())

In [ ]:
len(client_item_graph.g.nodes())

In [12]:
import pandas as pd

In [16]:
df = pd.read_csv('data/transactions.csv')
df.head()

   customer_id tr_datetime  mcc_code  tr_type    amount term_id
0     39026145  0 10:23:26      4814     1030  -2245.92     NaN
1     39026145  1 10:19:29      6011     7010  56147.89     NaN
2     39026145  1 10:20:56      4829     2330 -56147.89     NaN
3     39026145  1 10:39:54      5499     1010  -1392.47     NaN
4     39026145  2 15:33:42      5499     1010   -920.83     NaN

In [17]:
df['mcc_code'].unique()

array([4814, 6011, 4829, 5499, 5541, 5200, 5732, 6010, 5331, 5912, 5411,
       5812, 6012, 5719, 5722, 5621, 5814, 5921, 5941, 5691, 5813, 5211,
       4812, 5945, 5983, 5999, 5943, 5533, 6300, 7832, 8099, 5992, 3501,
       6536, 7997, 5641, 4722, 5661, 5651, 7011, 5699, 5942, 7298, 7999,
       5712, 5511, 5422, 5399, 4900, 7538, 5949, 5977, 5948, 5631, 5311,
       5462, 4112, 8999, 8021, 5714, 5251, 4789, 7542, 5947, 3000, 8043,
       5944, 5734, 5611, 5532, 4816, 7311, 5655, 6051, 7994, 5995, 5309,
       5964, 8299, 8244, 4111, 4511, 9399, 5441, 7922, 5261, 7699, 7995,
       7629, 5816, 5735, 5039, 5300, 5199, 4121, 5065, 7399, 7299, 8011,
       7230, 9222, 5946, 5131, 5994, 5231, 8071, 5094, 5047, 5072, 7210,
       5976, 5045, 7932, 4215, 5542, 5099, 5713, 4899, 7933, 5681, 5193,
       1711, 6211, 8398, 5599, 5993, 8062, 5169, 4214, 5733, 5013, 7221,
       5571, 7993, 5971, 5968, 7372, 5074, 5044, 5811, 5111, 8641, 7512,
       7523, 9311, 8220, 7991, 7996, 4784, 5931, 7841, 3351, 4411, 1799,
       5192, 5122,  742, 6513, 7278, 5969, 5970, 4131, 5965, 7395, 5950,
       5085, 7273, 5137, 5310, 7531, 7829, 7375, 2741, 5172, 8699, 7216,
       5451, 5967, 7338, 9402, 5697, 1731, 5940, 9211])

In [18]:
len(df['mcc_code'].unique())

184

In [19]:
ptls_train_df = pd.read_parquet('data/train_trx.parquet/')

In [20]:
ptls_train_df.head()

,customer_id,event_time,amount,mcc_code,tr_type,term_id,trx_count,target
0,10058778,"[23.35869212962963, 23.359502314814815, 36.498...","[13.420652589715486, -13.420652589715486, 14.6...","[2, 6, 3, 2, 2, 3, 2, 3, 2, 6, 6, 3, 10, 3, 2,...","[8, 13, 6, 3, 3, 23, 3, 11, 8, 19, 20, 6, 2, 6...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",142,1.0
1,10230827,"[0.25885416666666666, 1.5346412037037038, 1.65...","[13.015188216272872, -10.01949835204266, -9.76...","[3, 2, 5, 8, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 3, ...","[29, 3, 5, 5, 3, 3, 3, 4, 3, 3, 4, 3, 3, 4, 29...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",279,0.0
2,11681378,"[0.3015393518518519, 0.3589583333333333, 0.875...","[-8.41023807171957, -7.9242460340479255, -9.91...","[4, 7, 2, 2, 11, 5, 7, 6, 2, 7, 7, 3, 6, 7, 7,...","[4, 2, 27, 28, 2, 5, 2, 13, 3, 2, 2, 9, 13, 2,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",881,1.0
3,14123285,"[15.489155092592593, 21.68777777777778, 23.612...","[12.792045221523114, 12.216683253401992, -10.7...","[3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, ...","[11, 9, 16, 25, 25, 16, 11, 6, 16, 25, 11, 17,...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",1051,0.0
4,16536678,"[75.40552083333333, 75.59731481481481, 83.5602...","[14.336942434053569, -9.326395693771916, -9.32...","[2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, ...","[8, 4, 4, 4, 4, 8, 4, 4, 4, 8, 4, 4, 4, 4, 4, ...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",128,0.0

In [23]:
mcc_ids = {el for arr in ptls_train_df['mcc_code'] for el in arr}

In [25]:
print(mcc_ids)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185}

In [26]:
?df.to_parquet

Signature:
df.to_parquet(
    path: 'FilePath | WriteBuffer[bytes] | None' = None,
    engine: "Literal['auto', 'pyarrow', 'fastparquet']" = 'auto',
    compression: 'str | None' = 'snappy',
    index: 'bool | None' = None,
    partition_cols: 'list[str] | None' = None,
    storage_options: 'StorageOptions | None' = None,
    **kwargs,
) -> 'bytes | None'
Docstring:
Write a DataFrame to the binary parquet format.

This function writes the dataframe as a `parquet file
<https://parquet.apache.org/>`_. You can choose different parquet
backends, and have the option of compression. See
:ref:`the user guide <io.parquet>` for more details.

Parameters
----------
path : str, path object, file-like object, or None, default None
    String, path object (implementing ``os.PathLike[str]``), or file-like
    object implementing a binary ``write()`` function. If None, the result is
    returned as bytes. If a string or path, it will be used as Root Directory
    path when writing a partitioned dataset.

    .. versionchanged:: 1.2.0

    Previously this was "fname"

engine : {'auto', 'pyarrow', 'fastparquet'}, default 'auto'
    Parquet library to use. If 'auto', then the option
    ``io.parquet.engine`` is used. The default ``io.parquet.engine``
    behavior is to try 'pyarrow', falling back to 'fastparquet' if
    'pyarrow' is unavailable.
compression : str or None, default 'snappy'
    Name of the compression to use. Use ``None`` for no compression.
    Supported options: 'snappy', 'gzip', 'brotli', 'lz4', 'zstd'.
index : bool, default None
    If ``True``, include the dataframe's index(es) in the file output.
    If ``False``, they will not be written to the file.
    If ``None``, similar to ``True`` the dataframe's index(es)
    will be saved. However, instead of being saved as values,
    the RangeIndex will be stored as a range in the metadata so it
    doesn't require much space and is faster. Other indexes will
    be included as columns in the file output.
partition_cols : list, optional, default None
    Column names by which to partition the dataset.
    Columns are partitioned in the order they are given.
    Must be None if path is not a string.
storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

    .. versionadded:: 1.2.0

**kwargs
    Additional arguments passed to the parquet library. See
    :ref:`pandas io <io.parquet>` for more details.

Returns
-------
bytes if no path argument is provided else None

See Also
--------
read_parquet : Read a parquet file.
DataFrame.to_orc : Write an orc file.
DataFrame.to_csv : Write a csv file.
DataFrame.to_sql : Write to a sql table.
DataFrame.to_hdf : Write to hdf.

Notes
-----
This function requires either the `fastparquet
<https://pypi.org/project/fastparquet>`_ or `pyarrow
<https://arrow.apache.org/docs/python/>`_ library.

Examples
--------
>>> df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
>>> df.to_parquet('df.parquet.gzip',
...               compression='gzip')  # doctest: +SKIP
>>> pd.read_parquet('df.parquet.gzip')  # doctest: +SKIP
   col1  col2
0     1     3
1     2     4

If you want to get a buffer to the parquet content you can use a io.BytesIO
object, as long as you don't use partition_cols, which creates multiple files.

>>> import io
>>> f = io.BytesIO()
>>> df.to_parquet(f)
>>> f.seek(0)
0
>>> content = f.read()
File:      ~/.local/lib/python3.10/site-packages/pandas/core/frame.py
Type:      method

In [28]:
import pickle

with open('data/train_trx.parquet', 'rb') as f:
    data = pickle.load(f)

In [30]:
type(data)

list

In [31]:
data[0]

{'target': 1,
 'customer_id': 22899,
 'feature_arrays': {'mcc_code': array([ 3,  3,  1,  1,  2,  1,  1,  3,  1,  3,  2,  1,  2,  3,  1,  2,  7,
          8,  3,  1,  1,  1,  1,  3,  3,  2,  7,  2,  1,  3,  1,  2,  5,  5,
          6,  3,  1,  1,  5,  2,  5,  1,  5,  2,  1,  1,  1,  2,  5,  1,  3,
          3,  2,  2,  1,  3,  1,  6,  1,  3,  1,  1,  3,  3,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  3,  1,  3,  6,  1,  5,  2,  1,  3,  3,  4,  1,
          1,  4,  7,  6,  1,  1,  6,  1,  5,  6,  1,  1,  5,  5,  6,  7,  3,
          2,  7,  1,  5,  5, 49,  3,  1,  6,  2,  3,  1,  1,  1,  2,  2,  1,
          2,  1,  1,  1,  5,  3,  1,  7,  7,  6,  3,  2,  1,  1,  1,  3,  1,
          3,  1,  1,  1,  1,  1,  5,  5,  2,  6,  5,  1,  2,  3,  3,  1,  3,
          3,  2,  1,  3,  3,  1,  2,  1,  1,  3,  3,  1,  5,  4,  1,  1,  3,
          1,  1,  5,  5,  1,  3,  3,  3,  2,  6,  1,  1,  3,  6,  1,  3,  1,
          1,  1,  6,  2,  3,  1,  3,  1,  5,  5,  1,  1,  1,  1,  6,  1,  3,
          1,  2,  5,  1,  2,  5,  2,  3,  4,  4,  4,  1,  1,  5,  5,  7,  1,
          1,  1,  1,  5,  3,  3,  9,  9,  6, 26,  5,  1,  1]),
  'tr_type': array([ 3,  3,  2,  2,  8,  2,  7,  3,  2,  3,  8,  2,  8,  3,  2,  8,  1,
          1,  3,  2,  2, 17,  7,  3,  3, 10,  4,  8,  2,  3,  7,  5, 14, 13,
          4,  3,  7,  7,  6,  5,  6,  7,  6,  5,  2, 17,  7,  5,  6,  7,  3,
          3,  8,  8,  2,  3,  2,  4,  7,  3,  7,  7,  3,  3,  7,  2,  2,  2,
          2,  2,  2,  2,  2,  3,  2,  3,  4,  7, 12,  8,  7,  3,  3,  4, 17,
          2,  4,  4,  4, 17,  2,  4,  7,  6,  4,  7,  7, 18, 19,  4,  4,  3,
          8,  4,  7, 13, 14,  4,  3,  7,  4, 43,  3,  2, 27, 26,  8, 10,  2,
         43,  2,  7,  7, 12,  3,  7,  4,  4,  4,  3,  8,  2,  2,  2,  3,  2,
          3,  2,  2,  2,  7,  7, 13, 14,  8,  1,  6,  2,  5,  3,  3,  2,  3,
          3,  5,  2,  3,  3,  7,  5,  2,  2,  3,  3,  7,  6,  4, 17,  2,  3,
          7,  7, 14, 13,  2,  3,  3,  3, 16,  4,  2,  2,  3,  4,  7,  3,  2,
         17,  2,  4, 10,  3,  2,  3,  7, 18, 19,  7,  7, 17,  2,  4,  7,  3,
          7,  5,  6,  7, 49,  6,  5,  3,  4,  4,  4,  7,  7, 13, 14,  1,  7,
         17,  2,  7,  6,  3,  3,  1,  1,  4, 11,  6,  7,  2]),
  'amount': array([-0.44737662, -0.41051711, -0.56985036, -0.63415931,  0.55454771,
         -0.55087779,  0.61859108, -0.41051711, -0.56712191, -0.32499834,
          0.56985036, -0.56712191,  0.53298007, -0.41051711, -0.52737575,
          0.56985036, -0.44737662, -0.41976655, -0.41051711, -0.55798068,
         -0.70247355, -0.51594788,  0.52111071, -0.52111071, -0.32499834,
          0.45924424, -0.44730482,  0.65546231, -0.65546231, -0.3736693 ,
          0.72785831,  0.49611097, -0.48245049, -0.72741317, -0.47319835,
         -0.34652737,  0.53298007,  0.56120549, -0.53298007,  0.32499834,
         -0.32499834,  0.45480967, -0.4559534 ,  0.4559534 , -0.46894114,
         -0.44711003,  0.41051711,  0.41061266, -0.41061266,  0.53298007,
         -0.52177147, -0.43207748,  0.55798068,  0.62828946, -0.62366099,
         -0.41051711, -0.46894114, -0.4723737 ,  0.49611097, -0.49611097,
          0.56985036,  0.50580862, -0.50580862, -0.3736693 ,  0.67336064,
         -0.60672123, -0.60672123, -0.56985036, -0.49611097, -0.49611097,
         -0.49611097, -0.49611097, -0.48424217, -0.53298007, -0.48424217,
         -0.41051711, -0.41051711,  0.55454771, -0.55454771,  0.55454771,
          0.50580862, -0.50580862, -0.36181129, -0.53595391, -0.48289557,
         -0.49611097, -0.44571833, -0.49611097, -0.49179145, -0.48289557,
         -0.6164196 , -0.48708992,  0.65546231, -0.65546231, -0.4838418 ,
          0.69233366,  0.49611097, -0.69233366, -0.44737662, -0.43278187,
         -0.44732343, -0.34652737,  0.53298007, -0.49610567,  0.67703066,
         -0.67703066, -0.43207748, -0.44894869, -0.43207748,  0.55454771,
         -0.49524224,  0.61859108, -0.41051711, -0.6164196 , -0.48289557,
         -0.46894114,  0.5380498 ,  0.59961821, -0.61415569,  0.66516073,
         -0.66471559,  0.69233366,  0.43207748, -0.69233366, -0.41051711,
          0.5642459 , -0.42878711, -0.49611097, -0.50874048, -0.34652737,
          0.65546231, -0.52737575, -0.59485141, -0.56985036, -0.41051711,
         -0.53298007, -0.41051711, -0.46894114, -0.48424217, -0.56985036,
          0.46894114,  0.61859108, -0.61816381, -0.37324212,  0.64359241,
         -0.50746689, -0.61056824, -0.55454771,  0.48424217, -0.41051711,
         -0.41051711, -0.54693581, -0.41051711, -0.3736693 ,  0.53298007,
         -0.53298007, -0.3736693 , -0.32499834,  0.56985036,  0.51400801,
         -0.49611097, -0.41051711, -0.3736693 , -0.34472745,  0.62828946,
         -0.62828946, -0.49934057, -0.48289557, -0.50580862, -0.32227593,
          0.56985036,  0.61859108, -0.33789671, -0.58277344, -0.56712191,
         -0.41051711, -0.41051711, -0.45924424,  0.56985036, -0.50000715,
         -0.46894114, -0.44737662, -0.41051711, -0.52514276,  0.56985036,
         -0.41051711, -0.46894114, -0.48289557, -0.53298007, -0.49026998,
          0.52111071, -0.41051711, -0.51400801, -0.40491495,  0.52111071,
         -0.52111071, -0.27643327,  0.3736693 ,  0.56985036, -0.48289557,
         -0.50580862, -0.50651317,  0.3736693 , -0.34652737,  0.53298007,
          0.23879371, -0.23879371,  0.53557532,  0.49611097, -0.47713996,
          0.47713996, -0.23879371, -0.52414106, -0.49166441, -0.52825498,
          0.65625429,  0.43207748, -0.65546231, -0.41051711, -0.44731016,
          0.56985036, -0.48289557, -0.55454771,  0.61298655, -0.58172007,
         -0.46894114, -0.3736693 , -0.4627432 , -0.46163614, -0.51238787,
         -0.35317634, -0.51006614,  0.61859108, -0.60672123]),
  'term_id': array([     1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,  41728,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1, 202625,
          41728,      1,      1,  41728,  29541,      6,  41728, 171722,
          29541,  29541,  29541,  41728,  11758,      4,  32491, 227658,
          10896,      4,      4, 343471,      4,  33798, 343472, 343473,
              5,  23415, 220539, 220539,  29541,      5,  34038,  13616,
         110607, 171723, 171723, 171723,     11,  26067,  84201,  84201,
          41728,      5,  32491,  38341,  38341,  38341,      9,  38341,
             11,  38341,  38341,  23415, 123650,  38341,      5,      5,
           9950, 343474,      3,  38341,      7,      5,     11,  38341,
              2,      3,      4,  19903,      6,      7, 123650,      6,
         123650, 123650,      4,      2, 147966,      2, 220533,  12935,
          12935,      6,  29541,  29541,      6,      6,  79140,     10,
             10,      7,  70199,  41728, 123650,  79140,     11,  41728,
          38341,      9,  59918,   5674,   5674,  41728,     22,      8,
          12935,  12935,  29541,  29541,  29541,  29541, 171722,  96189,
          96189,  41728, 107101,     23,  29541,     22,     22, 171722,
             26,     26,     26,      4,  82390, 220533,  88226,  56427,
          56427,     21,     21, 177034,  29541,  96189,  96189,  33798,
             29,     30,     13, 220531, 220531,  41728,      1,      7,
         107101,  40021])},
 'event_time': array([  1.64357639,   2.87      ,   5.78633102,   6.51969907,
         28.44515046,  28.48238426,  48.57027778,  52.05112269,
         53.46085648,  56.42430556,  61.8353125 ,  61.84043981,
         61.87018519,  62.16251157,  62.58060185,  66.41180556,
         66.61289352,  66.64583333,  67.15240741,  67.40369213,
         82.63315972,  82.63333333,  83.64694444,  83.64915509,
         84.47030093,  86.59204861,  86.66322917,  87.4012037 ,
         87.55922454,  87.69645833,  98.80966435,  98.85122685,
         98.86541667,  98.86572917,  99.69465278, 109.38054398,
        110.53778935, 110.5390162 , 110.78001157, 110.90878472,
        110.90892361, 110.91802083, 110.91980324, 110.91984954,
        111.61263889, 111.61288194, 111.61483796, 111.6168287 ,
        111.61694444, 113.53104167, 113.54258102, 113.5446412 ,
        132.61460648, 145.68960648, 147.7359838 , 150.06152778,
        151.479375  , 163.87167824, 164.68697917, 164.6880787 ,
        164.68951389, 167.40881944, 167.40950231, 167.40986111,
        172.46607639, 172.47136574, 172.47158565, 172.47269676,
        172.47336806, 172.47400463, 172.47427083, 172.47466435,
        172.47563657, 172.47585648, 172.47594907, 175.06128472,
        175.91774306, 192.47569444, 192.4775463 , 192.4777662 ,
        197.37538194, 197.37623843, 197.37671296, 204.53344907,
        205.76982639, 205.76986111, 206.61869213, 206.74094907,
        206.82770833, 207.48980324, 207.4902662 , 208.80309028,
        210.65636574, 210.65880787, 210.80859954, 215.65074074,
        215.6666088 , 215.6675463 , 215.66759259, 215.87287037,
        216.26878472, 216.6646412 , 217.6846412 , 217.69509259,
        221.61229167, 221.61390046, 221.61407407, 221.78771991,
        222.35368056, 224.71539352, 228.57491898, 230.69665509,
        230.79452546, 230.85990741, 231.39658565, 231.3971412 ,
        231.41501157, 231.48350694, 231.48521991, 240.46765046,
        240.49141204, 250.465625  , 250.46731481, 250.46780093,
        252.05094907, 253.53111111, 255.16628472, 255.16716435,
        255.51090278, 257.9508912 , 260.49268519, 260.50215278,
        260.5025    , 260.77115741, 261.05865741, 261.48917824,
        262.19847222, 262.50123843, 262.50133102, 262.65188657,
        268.64362269, 271.4372338 , 271.44127315, 271.44134259,
        272.78453704, 273.4371412 , 273.44905093, 273.68868056,
        273.77886574, 273.7909375 , 274.09865741, 274.81836806,
        277.23083333, 277.41180556, 278.5197338 , 278.53032407,
        282.4890162 , 282.49166667, 283.53267361, 284.45596065,
        284.4831713 , 284.51741898, 285.05667824, 288.47090278,
        288.49532407, 288.50190972, 288.59950231, 289.62163194,
        289.62217593, 290.39769676, 314.4687037 , 319.48538194,
        319.48760417, 319.48771991, 319.49413194, 320.11111111,
        321.09332176, 323.80010417, 338.48013889, 338.82736111,
        339.55747685, 339.61275463, 340.10082176, 342.7309838 ,
        344.48984954, 347.09601852, 348.53986111, 349.69087963,
        349.69087963, 350.88665509, 352.44857639, 356.09383102,
        360.45104167, 360.45149306, 363.68865741, 363.69034722,
        363.69037037, 363.69076389, 376.46597222, 381.39701389,
        381.39711806, 386.87243056, 396.49065972, 396.79219907,
        397.42408565, 398.52331019, 398.5233912 , 407.45479167,
        407.52456019, 407.6662037 , 407.66625   , 408.39342593,
        408.69054398, 415.39946759, 421.49575231, 431.78618056,
        431.78954861, 431.79185185, 431.79193287, 431.81736111,
        438.37523148, 441.65042824, 441.65052083, 453.47565972,
        453.47850694, 453.75384259, 453.75940972, 454.72725694,
        454.91305556, 456.        , 456.        , 456.42291667,
        456.71828704, 456.71959491])}

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('data/transactions.csv')
df.head()

   customer_id tr_datetime  mcc_code  tr_type    amount term_id
0     39026145  0 10:23:26      4814     1030  -2245.92     NaN
1     39026145  1 10:19:29      6011     7010  56147.89     NaN
2     39026145  1 10:20:56      4829     2330 -56147.89     NaN
3     39026145  1 10:39:54      5499     1010  -1392.47     NaN
4     39026145  2 15:33:42      5499     1010   -920.83     NaN

In [39]:
df['mcc_code'].head()

0    4814
1    6011
2    4829
3    5499
4    5499
Name: mcc_code, dtype: int64

In [40]:
item_map = pd.read_csv('data/mcc_code_mapping.csv')
item_map.head()

   _orig_mcc_code  mcc_code
0            6011         2
1            6010         3
2            4814         4
3            5411         5
4            4829         6

In [41]:
df = df.rename(columns={'mcc_code': '_orig_mcc_code'})
df['_orig_mcc_code'] = df['_orig_mcc_code'].fillna("#EMPTY")

In [42]:
df = df.merge(item_map, on='_orig_mcc_code', how='left')
df.head()

,customer_id,tr_datetime,_orig_mcc_code,tr_type,amount,term_id,mcc_code
0,39026145,0 10:23:26,4814,1030,-2245.92,NaN,4
1,39026145,1 10:19:29,6011,7010,56147.89,NaN,2
2,39026145,1 10:20:56,4829,2330,-56147.89,NaN,6
3,39026145,1 10:39:54,5499,1010,-1392.47,NaN,7
4,39026145,2 15:33:42,5499,1010,-920.83,NaN,7

In [43]:
df = df.drop(columns = ['_orig_mcc_code'])
df.head()

   customer_id tr_datetime  tr_type    amount term_id  mcc_code
0     39026145  0 10:23:26     1030  -2245.92     NaN         4
1     39026145  1 10:19:29     7010  56147.89     NaN         2
2     39026145  1 10:20:56     2330 -56147.89     NaN         6
3     39026145  1 10:39:54     1010  -1392.47     NaN         7
4     39026145  2 15:33:42     1010   -920.83     NaN         7

In [67]:
mask_ids = {0, 7179, 10258, 8723, 31, 1583, 10295, 9793, 70, 13896, 5706, 10832, 10331, 5214, 10864, 5746, 5242, 6267, 3707, 1671, 3209, 3219, 11415, 162, 6842, 3259, 6334, 3783, 13010, 3802, 3291, 1761, 2788, 2804, 12026, 4352, 258, 5381, 2826, 14094, 7951, 4910, 314, 3386, 8506, 7998, 841, 2891, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168, 14169, 14170, 14171, 14172, 14173, 7518, 14174, 14175, 14176, 14177, 14178, 14179, 14180, 14182, 14183, 14184, 14185, 14187, 14188, 14189, 14190, 14191, 14192, 14193, 6514, 14194, 14195, 14196, 10614, 14197, 14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14209, 14210, 14211, 14212, 14213, 14214, 14217, 14218, 14219, 14220, 14221, 5008, 14224, 14226, 14228, 14233, 14234, 4508, 14237, 14238, 416, 14240, 14241, 14242, 5547, 8621, 14254, 14256, 14261, 4537, 14272, 14280, 14287, 7633, 14289, 12244, 4056, 9178, 14298, 14299, 10207, 4579, 14310, 12779, 5108}
changed_ids = {0, 14336, 13831, 7179, 10258, 8723, 7193, 13338, 31, 1583, 10295, 9793, 10821, 70, 13896, 5706, 10832, 2139, 92, 10331, 5214, 6254, 4207, 10864, 5746, 12409, 5242, 6267, 3707, 9340, 9850, 9853, 13440, 13945, 5763, 13956, 1671, 3209, 650, 7817, 3219, 1684, 3735, 11415, 2718, 162, 1186, 9382, 9899, 2225, 10936, 6842, 3259, 6334, 4293, 3783, 4811, 13010, 3802, 3291, 9434, 1249, 1761, 2788, 14215, 10993, 2804, 9976, 12026, 4352, 258, 13058, 11524, 1285, 5381, 12036, 2826, 14094, 7951, 1811, 14217, 1834, 10538, 813, 4910, 10032, 6456, 12600, 314, 3386, 8506, 7998, 11587, 327, 841, 3401, 2891, 14154, 336, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168, 13658, 14169, 14170, 14171, 7518, 14172, 14173, 14174, 14175, 14176, 14177, 14178, 14179, 14180, 12136, 14182, 14183, 14184, 14185, 12141, 8558, 14186, 14187, 14188, 6514, 6003, 14189, 14190, 10614, 14191, 14192, 14193, 14194, 14195, 14196, 14197, 14198, 14199, 14200, 14201, 3970, 14202, 14203, 14204, 14205, 14206, 14207, 14208, 14209, 14210, 14211, 14212, 14213, 14214, 5008, 14216, 11666, 14218, 14219, 14220, 14221, 14222, 14223, 13209, 3994, 14225, 4508, 14226, 14229, 8095, 416, 14228, 14233, 14234, 14237, 14238, 14239, 14240, 14241, 14242, 14244, 5547, 14245, 8621, 14251, 14252, 14254, 14256, 14260, 14261, 4537, 10681, 14266, 14267, 14271, 14272, 14276, 2503, 9159, 14280, 14224, 14287, 7633, 14289, 3540, 12244, 14293, 4056, 9178, 14298, 14299, 14301, 10207, 14305, 4579, 14310, 12779, 8179, 5108, 10228, 14332}

In [68]:
len(mask_ids)

141

In [69]:
len(changed_ids)

229

In [70]:
changed_ids - mask_ids

{92,
 327,
 336,
 650,
 813,
 1186,
 1249,
 1285,
 1684,
 1811,
 1834,
 2139,
 2225,
 2503,
 2718,
 3401,
 3540,
 3735,
 3970,
 3994,
 4207,
 4293,
 4811,
 5763,
 6003,
 6254,
 6456,
 7193,
 7817,
 8095,
 8179,
 8558,
 9159,
 9340,
 9382,
 9434,
 9850,
 9853,
 9899,
 9976,
 10032,
 10228,
 10538,
 10681,
 10821,
 10936,
 10993,
 11524,
 11587,
 11666,
 12036,
 12136,
 12141,
 12409,
 12600,
 13058,
 13209,
 13338,
 13440,
 13658,
 13831,
 13945,
 13956,
 14154,
 14186,
 14207,
 14208,
 14215,
 14216,
 14222,
 14223,
 14225,
 14229,
 14239,
 14244,
 14245,
 14251,
 14252,
 14260,
 14266,
 14267,
 14271,
 14276,
 14293,
 14301,
 14305,
 14332,
 14336}

In [2]:
%cd ..

/path/to/repo/Documents/my-coles-gnn-experimetns

In [38]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph, ClientItemGraphFull

In [39]:
graph_1 = ClientItemGraphFull.from_graph_file('./scenario_gender/data/graphs/weighted/train_graph.bin', device_name = 'cpu')
graph_1

ClientItemGraphFull(g=Graph(num_nodes=14344, num_edges=573328,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'weight': Scheme(shape=(), dtype=torch.float32)}), device_name='cpu')

In [40]:
graph_2 = ClientItemGraph.from_graph_file('./scenario_gender/data/graphs/weighted/train_graph.bin', device_name='cpu')
graph_2

ClientItemGraph(g=Graph(num_nodes=14344, num_edges=573328,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'weight': Scheme(shape=(), dtype=torch.float32)}), device_name='cpu')

In [55]:
graph_2.g.number_of_nodes() == graph_1.g.number_of_nodes()

True

In [59]:
n_nodes = graph_2.g.number_of_nodes()
n_nodes

14344

In [57]:
graph_1.g.ndata['_ID']

tensor([    0,     1,     2,  ..., 14341, 14342, 14343])

In [56]:
graph_2.g.ndata['_ID']

tensor([    0,     1,     2,  ..., 15181, 15182, 15183])

In [50]:
torch.all(graph_1.g.ndata['_ID'] == torch.arange(0, n_nodes))

tensor(True)

In [49]:
torch.all(graph_2.g.ndata['_ID'] == torch.arange(0, n_nodes))

tensor(False)

True

In [37]:
for expected_i, i in enumerate(graph_2.g.ndata['_ID']):
    i = int(i)
    if i != expected_i:
        print(i, expected_i)

10 9
11 10
12 11
13 12
14 13
15 14
16 15
18 16
19 17
20 18
21 19
22 20
23 21
24 22
25 23
27 24
28 25
29 26
30 27
31 28
33 29
34 30
35 31
36 32
37 33
38 34
39 35
40 36
41 37
42 38
43 39
44 40
45 41
46 42
47 43
48 44
49 45
50 46
51 47
52 48
53 49
54 50
55 51
57 52
58 53
59 54
60 55
61 56
62 57
63 58
64 59
65 60
66 61
67 62
68 63
69 64
70 65
71 66
72 67
73 68
74 69
75 70
76 71
77 72
78 73
79 74
80 75
81 76
83 77
84 78
85 79
86 80
88 81
89 82
90 83
91 84
92 85
93 86
95 87
96 88
97 89
98 90
99 91
100 92
101 93
102 94
103 95
104 96
105 97
106 98
107 99
108 100
109 101
110 102
111 103
112 104
113 105
114 106
115 107
117 108
118 109
119 110
120 111
121 112
122 113
123 114
124 115
125 116
126 117
127 118
128 119
129 120
130 121
131 122
132 123
133 124
134 125
135 126
136 127
137 128
139 129
140 130
141 131
142 132
144 133
145 134
146 135
147 136
148 137
149 138
150 139
151 140
152 141
153 142
154 143
155 144
156 145
157 146
158 147
159 148
160 149
161 150
162 151
163 152
164 153
165 154
166 155
167 156
168 157
169 158
170 159
171 160
172 161
173 162
174 163
175 164
176 165
177 166
178 167
179 168
180 169
181 170
182 171
183 172
185 173
186 174
187 175
188 176
189 177
190 178
191 179
192 180
193 181
194 182
195 183
196 184
197 185
199 186
200 187
201 188
202 189
203 190
204 191
205 192
206 193
207 194
208 195
209 196
210 197
211 198
212 199
213 200
214 201
215 202
216 203
217 204
218 205
219 206
220 207
221 208
222 209
223 210
224 211
225 212
226 213
227 214
228 215
229 216
230 217
231 218
232 219
233 220
234 221
235 222
236 223
237 224
238 225
239 226
240 227
241 228
242 229
243 230
244 231
245 232
246 233
247 234
248 235
249 236
250 237
251 238
252 239
253 240
254 241
255 242
256 243
257 244
258 245
259 246
260 247
261 248
262 249
263 250
264 251
265 252
266 253
267 254
268 255
269 256
270 257
271 258
272 259
273 260
274 261
275 262
276 263
277 264
278 265
279 266
280 267
282 268
284 269
285 270
286 271
287 272
288 273
289 274
290 275
291 276
292 277
293 278
294 279
295 280
296 281
298 282
299 283
300 284
301 285
302 286
303 287
304 288
305 289
306 290
307 291
308 292
309 293
310 294
311 295
312 296
313 297
314 298
315 299
316 300
317 301
318 302
319 303
320 304
321 305
322 306
323 307
324 308
325 309
326 310
327 311
328 312
329 313
330 314
331 315
332 316
333 317
334 318
335 319
336 320
337 321
339 322
340 323
341 324
342 325
343 326
344 327
345 328
346 329
347 330
348 331
349 332
350 333
352 334
353 335
354 336
355 337
356 338
357 339
358 340
359 341
360 342
361 343
363 344
364 345
365 346
366 347
367 348
368 349
370 350
371 351
372 352
373 353
374 354
375 355
376 356
377 357
378 358
379 359
380 360
381 361
382 362
383 363
384 364
385 365
386 366
387 367
388 368
389 369
390 370
391 371
392 372
393 373
394 374
395 375
396 376
397 377
398 378
399 379
400 380
402 381
403 382
405 383
406 384
407 385
408 386
409 387
410 388
412 389
413 390
414 391
415 392
416 393
417 394
418 395
419 396
420 397
421 398
422 399
423 400
424 401
425 402
426 403
427 404
429 405
430 406
431 407
432 408
434 409
435 410
436 411
437 412
438 413
439 414
440 415
441 416
442 417
443 418
444 419
445 420
446 421
447 422
448 423
449 424
450 425
451 426
452 427
453 428
454 429
456 430
457 431
458 432
459 433
460 434
461 435
462 436
463 437
464 438
465 439
466 440
467 441
468 442
469 443
470 444
471 445
472 446
473 447
474 448
475 449
476 450
477 451
478 452
479 453
480 454
481 455
482 456
483 457
484 458
485 459
486 460
487 461
488 462
489 463
490 464
491 465
492 466
493 467
494 468
495 469
496 470
497 471
498 472
499 473
500 474
501 475
502 476
503 477
504 478
505 479
506 480
507 481
508 482
509 483
510 484
511 485
512 486
513 487
514 488
515 489
516 490
517 491
518 492
519 493
520 494
521 495
522 496
523 497
524 498
525 499
526 500
527 501
528 502
529 503
530 504
531 505
532 506
533 507
534 508
535 509
536 510
538 511
539 512
540 513
541 514
542 515
543 516
544 517
545 518
546 519
547 520
548 521
549 522
550 523
551 524
552 525
553 526
554 527
555 528
556 529
557 530
558 531
559 532
560 533
561 534
562 535
563 536
564 537
565 538
566 539
567 540
568 541
569 542
570 543
571 544
573 545
574 546
575 547
577 548
579 549
580 550
581 551
582 552
583 553
584 554
585 555
586 556
587 557
588 558
589 559
590 560
593 561
594 562
596 563
597 564
598 565
599 566
600 567
601 568
602 569
603 570
604 571
605 572
606 573
607 574
608 575
609 576
610 577
611 578
612 579
614 580
615 581
616 582
618 583
619 584
620 585
621 586
622 587
623 588
624 589
625 590
626 591
627 592
628 593
629 594
630 595
631 596
632 597
633 598
634 599
635 600
636 601
637 602
639 603
640 604
642 605
643 606
644 607
645 608
646 609
647 610
648 611
649 612
650 613
651 614
652 615
653 616
654 617
655 618
656 619
657 620
658 621
659 622
660 623
661 624
663 625
664 626
665 627
666 628
667 629
668 630
669 631
670 632
671 633
672 634
673 635
674 636
675 637
676 638
677 639
678 640
679 641
680 642
681 643
682 644
683 645
684 646
685 647
686 648
687 649
688 650
689 651
690 652
691 653
692 654
693 655
694 656
695 657
696 658
697 659
698 660
699 661
700 662
701 663
702 664
703 665
704 666
705 667
706 668
707 669
708 670
709 671
710 672
714 673
715 674
716 675
717 676
719 677
720 678
721 679
722 680
723 681
724 682
725 683
726 684
727 685
728 686
729 687
730 688
731 689
733 690
734 691
735 692
736 693
737 694
738 695
739 696
740 697
741 698
742 699
743 700
744 701
745 702
746 703
747 704
748 705
749 706
750 707
752 708
753 709
754 710
755 711
756 712
757 713
758 714
759 715
760 716
761 717
762 718
763 719
764 720
765 721
766 722
767 723
768 724
769 725
770 726
771 727
772 728
773 729
774 730
775 731
776 732
777 733
778 734
779 735
780 736
781 737
782 738
783 739
784 740
785 741
786 742
787 743
788 744
789 745
790 746
791 747
792 748
793 749
794 750
795 751
796 752
797 753
798 754
799 755
800 756
801 757
802 758
803 759
804 760
805 761
806 762
807 763
808 764
809 765
810 766
812 767
813 768
814 769
816 770
817 771
818 772
819 773
820 774
821 775
822 776
823 777
824 778
825 779
826 780
827 781
828 782
829 783
830 784
831 785
832 786
834 787
835 788
836 789
838 790
839 791
840 792
841 793
842 794
843 795
844 796
845 797
846 798
847 799
849 800
850 801
851 802
852 803
853 804
854 805
855 806
856 807
857 808
858 809
859 810
860 811
861 812
862 813
863 814
864 815
865 816
866 817
867 818
868 819
869 820
870 821
871 822
872 823
874 824
875 825
876 826
877 827
878 828
879 829
880 830
881 831
882 832
883 833
884 834
885 835
886 836
887 837
888 838
889 839
890 840
891 841
892 842
893 843
894 844
896 845
897 846
898 847
899 848
900 849
901 850
903 851
904 852
905 853
906 854
907 855
908 856
909 857
910 858
911 859
912 860
913 861
914 862
916 863
917 864
918 865
919 866
920 867
921 868
922 869
923 870
926 871
927 872
928 873
929 874
930 875
931 876
932 877
933 878
934 879
935 880
936 881
937 882
938 883
939 884
940 885
941 886
942 887
943 888
944 889
945 890
946 891
947 892
948 893
949 894
950 895
951 896
952 897
953 898
954 899
955 900
956 901
957 902
958 903
959 904
960 905
961 906
962 907
963 908
964 909
965 910
966 911
967 912
968 913
969 914
970 915
971 916
972 917
973 918
974 919
975 920
976 921
977 922
978 923
979 924
980 925
982 926
983 927
984 928
985 929
986 930
987 931
988 932
989 933
990 934
994 935
995 936
996 937
997 938
998 939
999 940
1000 941
1001 942
1002 943
1003 944
1004 945
1005 946
1006 947
1008 948
1009 949
1010 950
1011 951
1012 952
1013 953
1014 954
1015 955
1016 956
1017 957
1018 958
1020 959
1021 960
1022 961
1023 962
1024 963
1025 964
1026 965
1027 966
1028 967
1029 968
1030 969
1031 970
1032 971
1033 972
1034 973
1035 974
1036 975
1037 976
1038 977
1039 978
1040 979
1041 980
1042 981
1043 982
1044 983
1045 984
1046 985
1047 986
1048 987
1049 988
1050 989
1051 990
1052 991
1053 992
1054 993
1055 994
1056 995
1057 996
1058 997
1059 998
1060 999
1061 1000
1062 1001
1064 1002
1065 1003
1067 1004
1068 1005
1069 1006
1070 1007
1071 1008
1072 1009
1073 1010
1074 1011
1075 1012
1076 1013
1078 1014
1079 1015
1080 1016
1081 1017
1082 1018
1083 1019
1084 1020
1085 1021
1086 1022
1087 1023
1088 1024
1089 1025
1090 1026
1091 1027
1092 1028
1093 1029
1094 1030
1095 1031
1096 1032
1097 1033
1098 1034
1099 1035
1100 1036
1101 1037
1102 1038
1103 1039
1104 1040
1105 1041
1106 1042
1107 1043
1108 1044
1109 1045
1111 1046
1112 1047
1113 1048
1114 1049
1115 1050
1116 1051
1117 1052
1118 1053
1119 1054
1120 1055
1121 1056
1122 1057
1123 1058
1124 1059
1125 1060
1126 1061
1127 1062
1128 1063
1129 1064
1130 1065
1131 1066
1132 1067
1133 1068
1134 1069
1135 1070
1136 1071
1138 1072
1139 1073
1140 1074
1141 1075
1142 1076
1143 1077
1144 1078
1145 1079
1146 1080
1147 1081
1148 1082
1149 1083
1150 1084
1151 1085
1152 1086
1153 1087
1154 1088
1155 1089
1156 1090
1157 1091
1158 1092
1159 1093
1160 1094
1161 1095
1162 1096
1163 1097
1164 1098
1165 1099
1166 1100
1167 1101
1168 1102
1169 1103
1170 1104
1171 1105
1172 1106
1173 1107
1174 1108
1175 1109
1176 1110
1177 1111
1178 1112
1179 1113
1180 1114
1182 1115
1183 1116
1184 1117
1185 1118
1186 1119
1187 1120
1188 1121
1190 1122
1191 1123
1192 1124
1193 1125
1194 1126
1195 1127
1196 1128
1197 1129
1198 1130
1199 1131
1200 1132
1201 1133
1202 1134
1203 1135
1204 1136
1205 1137
1206 1138
1207 1139
1208 1140
1211 1141
1212 1142
1213 1143
1214 1144
1215 1145
1216 1146
1217 1147
1218 1148
1219 1149
1220 1150
1221 1151
1222 1152
1223 1153
1224 1154
1225 1155
1226 1156
1227 1157
1228 1158
1229 1159
1230 1160
1231 1161
1232 1162
1233 1163
1234 1164
1235 1165
1236 1166
1237 1167
1239 1168
1240 1169
1241 1170
1242 1171
1243 1172
1244 1173
1245 1174
1246 1175
1247 1176
1248 1177
1249 1178
1250 1179
1252 1180
1253 1181
1254 1182
1255 1183
1256 1184
1257 1185
1258 1186
1259 1187
1260 1188
1261 1189
1262 1190
1263 1191
1264 1192
1265 1193
1266 1194
1267 1195
1268 1196
1269 1197
1270 1198
1271 1199
1272 1200
1273 1201
1274 1202
1275 1203
1276 1204
1277 1205
1278 1206
1279 1207
1280 1208
1281 1209
1282 1210
1283 1211
1285 1212
1286 1213
1287 1214
1288 1215
1289 1216
1290 1217
1291 1218
1292 1219
1293 1220
1294 1221
1295 1222
1296 1223
1297 1224
1298 1225
1299 1226
1300 1227
1301 1228
1302 1229
1303 1230
1304 1231
1305 1232
1306 1233
1307 1234
1308 1235
1309 1236
1310 1237
1311 1238
1312 1239
1313 1240
1314 1241
1315 1242
1316 1243
1317 1244
1318 1245
1319 1246
1320 1247
1321 1248
1322 1249
1323 1250
1324 1251
1325 1252
1326 1253
1327 1254
1328 1255
1329 1256
1330 1257
1331 1258
1332 1259
1333 1260
1334 1261
1335 1262
1336 1263
1337 1264
1338 1265
1339 1266
1340 1267
1341 1268
1342 1269
1343 1270
1344 1271
1345 1272
1346 1273
1347 1274
1348 1275
1349 1276
1350 1277
1352 1278
1353 1279
1354 1280
1355 1281
1356 1282
1357 1283
1358 1284
1359 1285
1360 1286
1361 1287
1362 1288
1364 1289
1365 1290
1366 1291
1367 1292
1368 1293
1369 1294
1370 1295
1371 1296
1372 1297
1373 1298
1374 1299
1375 1300
1376 1301
1377 1302
1379 1303
1380 1304
1381 1305
1382 1306
1383 1307
1384 1308
1386 1309
1387 1310
1388 1311
1389 1312
1390 1313
1391 1314
1392 1315
1393 1316
1394 1317
1395 1318
1396 1319
1397 1320
1398 1321
1399 1322
1400 1323
1401 1324
1402 1325
1403 1326
1404 1327
1405 1328
1406 1329
1407 1330
1408 1331
1409 1332
1410 1333
1411 1334
1412 1335
1413 1336
1414 1337
1415 1338
1416 1339
1417 1340
1418 1341
1419 1342
1420 1343
1421 1344
1422 1345
1423 1346
1424 1347
1425 1348
1426 1349
1427 1350
1428 1351
1429 1352
1430 1353
1431 1354
1432 1355
1433 1356
1434 1357
1435 1358
1436 1359
1437 1360
1438 1361
1439 1362
1440 1363
1441 1364
1442 1365
1443 1366
1444 1367
1445 1368
1446 1369
1447 1370
1448 1371
1449 1372
1450 1373
1451 1374
1452 1375
1453 1376
1454 1377
1455 1378
1456 1379
1457 1380
1458 1381
1459 1382
1461 1383
1462 1384
1463 1385
1464 1386
1465 1387
1466 1388
1467 1389
1468 1390
1469 1391
1470 1392
1471 1393
1472 1394
1473 1395
1474 1396
1475 1397
1476 1398
1478 1399
1479 1400
1480 1401
1481 1402
1482 1403
1483 1404
1484 1405
1485 1406
1486 1407
1487 1408
1488 1409
1489 1410
1490 1411
1491 1412
1492 1413
1493 1414
1494 1415
1495 1416
1496 1417
1497 1418
1498 1419
1499 1420
1500 1421
1501 1422
1502 1423
1503 1424
1504 1425
1506 1426
1507 1427
1508 1428
1509 1429
1510 1430
1511 1431
1512 1432
1513 1433
1514 1434
1515 1435
1517 1436
1518 1437
1519 1438
1520 1439
1521 1440
1522 1441
1523 1442
1524 1443
1525 1444
1526 1445
1527 1446
1528 1447
1529 1448
1530 1449
1531 1450
1532 1451
1533 1452
1534 1453
1535 1454
1536 1455
1537 1456
1538 1457
1539 1458
1540 1459
1541 1460
1542 1461
1543 1462
1544 1463
1545 1464
1546 1465
1547 1466
1548 1467
1549 1468
1550 1469
1551 1470
1553 1471
1554 1472
1555 1473
1557 1474
1558 1475
1559 1476
1560 1477
1561 1478
1562 1479
1563 1480
1564 1481
1565 1482
1566 1483
1567 1484
1568 1485
1569 1486
1570 1487
1571 1488
1573 1489
1574 1490
1575 1491
1577 1492
1579 1493
1580 1494
1581 1495
1582 1496
1583 1497
1584 1498
1585 1499
1586 1500
1587 1501
1588 1502
1589 1503
1590 1504
1591 1505
1592 1506
1593 1507
1594 1508
1595 1509
1596 1510
1597 1511
1598 1512
1599 1513
1600 1514
1601 1515
1602 1516
1603 1517
1604 1518
1605 1519
1606 1520
1607 1521
1608 1522
1609 1523
1610 1524
1611 1525
1612 1526
1613 1527
1614 1528
1615 1529
1616 1530
1617 1531
1618 1532
1619 1533
1620 1534
1621 1535
1622 1536
1623 1537
1624 1538
1625 1539
1626 1540
1627 1541
1628 1542
1629 1543
1630 1544
1631 1545
1632 1546
1633 1547
1635 1548
1636 1549
1637 1550
1638 1551
1639 1552
1640 1553
1641 1554
1642 1555
1643 1556
1644 1557
1645 1558
1646 1559
1647 1560
1648 1561
1649 1562
1650 1563
1651 1564
1652 1565
1653 1566
1654 1567
1655 1568
1656 1569
1657 1570
1658 1571
1659 1572
1660 1573
1661 1574
1662 1575
1663 1576
1664 1577
1665 1578
1666 1579
1667 1580
1668 1581
1669 1582
1670 1583
1671 1584
1672 1585
1673 1586
1674 1587
1676 1588
1677 1589
1678 1590
1679 1591
1680 1592
1681 1593
1682 1594
1683 1595
1684 1596
1685 1597
1686 1598
1687 1599
1688 1600
1689 1601
1690 1602
1693 1603
1695 1604
1696 1605
1697 1606
1699 1607
1700 1608
1701 1609
1702 1610
1703 1611
1704 1612
1705 1613
1706 1614
1707 1615
1708 1616
1709 1617
1710 1618
1711 1619
1712 1620
1713 1621
1714 1622
1715 1623
1716 1624
1717 1625
1718 1626
1719 1627
1720 1628
1721 1629
1722 1630
1723 1631
1724 1632
1725 1633
1726 1634
1727 1635
1728 1636
1729 1637
1730 1638
1732 1639
1733 1640
1734 1641
1735 1642
1736 1643
1737 1644
1738 1645
1739 1646
1740 1647
1741 1648
1742 1649
1743 1650
1744 1651
1745 1652
1746 1653
1747 1654
1748 1655
1749 1656
1750 1657
1751 1658
1752 1659
1753 1660
1754 1661
1755 1662
1756 1663
1757 1664
1758 1665
1759 1666
1760 1667
1762 1668
1763 1669
1764 1670
1765 1671
1766 1672
1767 1673
1768 1674
1769 1675
1770 1676
1771 1677
1772 1678
1773 1679
1774 1680
1775 1681
1776 1682
1777 1683
1778 1684
1779 1685
1780 1686
1781 1687
1782 1688
1783 1689
1786 1690
1787 1691
1788 1692
1789 1693
1790 1694
1791 1695
1792 1696
1793 1697
1794 1698
1795 1699
1796 1700
1797 1701
1798 1702
1799 1703
1800 1704
1801 1705
1802 1706
1803 1707
1804 1708
1805 1709
1806 1710
1807 1711
1808 1712
1809 1713
1810 1714
1811 1715
1812 1716
1813 1717
1814 1718
1815 1719
1816 1720
1817 1721
1818 1722
1819 1723
1820 1724
1821 1725
1822 1726
1823 1727
1824 1728
1825 1729
1826 1730
1827 1731
1828 1732
1829 1733
1830 1734
1831 1735
1832 1736
1833 1737
1834 1738
1836 1739
1837 1740
1838 1741
1839 1742
1840 1743
1841 1744
1842 1745
1843 1746
1844 1747
1845 1748
1846 1749
1847 1750
1848 1751
1849 1752
1850 1753
1851 1754
1852 1755
1853 1756
1854 1757
1855 1758
1856 1759
1857 1760
1858 1761
1859 1762
1860 1763
1861 1764
1863 1765
1864 1766
1865 1767
1866 1768
1867 1769
1868 1770
1869 1771
1871 1772
1873 1773
1874 1774
1875 1775
1877 1776
1879 1777
1880 1778
1881 1779
1882 1780
1884 1781
1885 1782
1886 1783
1887 1784
1888 1785
1889 1786
1890 1787
1891 1788
1892 1789
1893 1790
1894 1791
1895 1792
1896 1793
1897 1794
1898 1795
1899 1796
1900 1797
1901 1798
1902 1799
1903 1800
1904 1801
1905 1802
1906 1803
1907 1804
1908 1805
1909 1806
1910 1807
1911 1808
1912 1809
1913 1810
1914 1811
1915 1812
1916 1813
1917 1814
1918 1815
1919 1816
1920 1817
1921 1818
1922 1819
1923 1820
1924 1821
1925 1822
1926 1823
1927 1824
1928 1825
1929 1826
1932 1827
1933 1828
1934 1829
1935 1830
1936 1831
1937 1832
1938 1833
1939 1834
1940 1835
1941 1836
1942 1837
1943 1838
1944 1839
1945 1840
1946 1841
1947 1842
1948 1843
1949 1844
1950 1845
1953 1846
1954 1847
1955 1848
1956 1849
1957 1850
1958 1851
1959 1852
1960 1853
1961 1854
1962 1855
1963 1856
1964 1857
1966 1858
1967 1859
1968 1860
1969 1861
1970 1862
1971 1863
1972 1864
1973 1865
1974 1866
1975 1867
1976 1868
1977 1869
1978 1870
1979 1871
1981 1872
1982 1873
1983 1874
1984 1875
1985 1876
1986 1877
1987 1878
1989 1879
1990 1880
1991 1881
1992 1882
1993 1883
1994 1884
1995 1885
1996 1886
1997 1887
1998 1888
1999 1889
2000 1890
2001 1891
2003 1892
2004 1893
2005 1894
2006 1895
2007 1896
2008 1897
2009 1898
2010 1899
2011 1900
2012 1901
2013 1902
2014 1903
2015 1904
2016 1905
2017 1906
2018 1907
2019 1908
2020 1909
2021 1910
2022 1911
2023 1912
2024 1913
2025 1914
2026 1915
2027 1916
2028 1917
2029 1918
2030 1919
2031 1920
2032 1921
2033 1922
2034 1923
2035 1924
2036 1925
2038 1926
2039 1927
2040 1928
2041 1929
2042 1930
2043 1931
2044 1932
2045 1933
2046 1934
2047 1935
2048 1936
2050 1937
2051 1938
2052 1939
2053 1940
2054 1941
2055 1942
2056 1943
2057 1944
2058 1945
2059 1946
2060 1947
2061 1948
2062 1949
2063 1950
2064 1951
2065 1952
2066 1953
2067 1954
2068 1955
2069 1956
2070 1957
2071 1958
2072 1959
2073 1960
2074 1961
2075 1962
2076 1963
2077 1964
2078 1965
2079 1966
2080 1967
2081 1968
2082 1969
2083 1970
2084 1971
2085 1972
2086 1973
2088 1974
2089 1975
2090 1976
2091 1977
2093 1978
2094 1979
2095 1980
2096 1981
2097 1982
2098 1983
2099 1984
2100 1985
2101 1986
2102 1987
2103 1988
2104 1989
2105 1990
2106 1991
2107 1992
2108 1993
2110 1994
2111 1995
2112 1996
2113 1997
2114 1998
2115 1999
2116 2000
2117 2001
2118 2002
2119 2003
2120 2004
2121 2005
2122 2006
2123 2007
2124 2008
2125 2009
2126 2010
2127 2011
2128 2012
2129 2013
2130 2014
2131 2015
2132 2016
2133 2017
2134 2018
2135 2019
2136 2020
2137 2021
2138 2022
2139 2023
2140 2024
2141 2025
2142 2026
2143 2027
2144 2028
2145 2029
2146 2030
2147 2031
2148 2032
2149 2033
2150 2034
2151 2035
2152 2036
2153 2037
2154 2038
2155 2039
2156 2040
2157 2041
2158 2042
2159 2043
2160 2044
2161 2045
2162 2046
2163 2047
2164 2048
2165 2049
2166 2050
2167 2051
2168 2052
2169 2053
2170 2054
2171 2055
2172 2056
2173 2057
2174 2058
2175 2059
2176 2060
2177 2061
2178 2062
2179 2063
2180 2064
2181 2065
2182 2066
2183 2067
2184 2068
2185 2069
2188 2070
2189 2071
2190 2072
2191 2073
2192 2074
2194 2075
2195 2076
2196 2077
2197 2078
2198 2079
2199 2080
2200 2081
2201 2082
2202 2083
2203 2084
2204 2085
2205 2086
2207 2087
2208 2088
2209 2089
2210 2090
2211 2091
2212 2092
2213 2093
2214 2094
2215 2095
2216 2096
2217 2097
2218 2098
2219 2099
2220 2100
2221 2101
2222 2102
2223 2103
2224 2104
2225 2105
2226 2106
2227 2107
2229 2108
2230 2109
2231 2110
2232 2111
2233 2112
2234 2113
2235 2114
2236 2115
2237 2116
2238 2117
2239 2118
2240 2119
2241 2120
2242 2121
2243 2122
2244 2123
2245 2124
2246 2125
2247 2126
2248 2127
2249 2128
2251 2129
2252 2130
2253 2131
2255 2132
2256 2133
2257 2134
2258 2135
2259 2136
2260 2137
2261 2138
2262 2139
2263 2140
2264 2141
2265 2142
2266 2143
2267 2144
2268 2145
2269 2146
2270 2147
2271 2148
2272 2149
2273 2150
2274 2151
2275 2152
2276 2153
2277 2154
2278 2155
2279 2156
2280 2157
2281 2158
2282 2159
2283 2160
2285 2161
2286 2162
2287 2163
2288 2164
2289 2165
2290 2166
2291 2167
2292 2168
2294 2169
2295 2170
2296 2171
2297 2172
2298 2173
2299 2174
2300 2175
2301 2176
2303 2177
2304 2178
2305 2179
2306 2180
2307 2181
2308 2182
2309 2183
2310 2184
2311 2185
2312 2186
2313 2187
2314 2188
2315 2189
2316 2190
2317 2191
2318 2192
2319 2193
2320 2194
2321 2195
2322 2196
2323 2197
2324 2198
2325 2199
2326 2200
2327 2201
2328 2202
2330 2203
2334 2204
2335 2205
2336 2206
2337 2207
2338 2208
2339 2209
2340 2210
2341 2211
2342 2212
2343 2213
2344 2214
2345 2215
2346 2216
2347 2217

In [35]:
import torch

In [4]:
from ptls_extension_2024_research.frames.gnn.gnn_module import ColesBatchToSubgraphConverter

In [63]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph

In [1]:
!ls data/graphs/weighted/full_graph.bin

adj_embs.pt
adj_feats__cosine__similarities.pickle
bins__adj_embs-cosine_similarity-deleted_empty_bins.pickle
bins__adj_embs-cosine_similarity-no_postprocessing__backup.pickle
bins__adj_embs-cosine_similarity-no_postprocessing.pickle
bins__adj_embs-tuple_tuple_set-cosine_similarity-no_postprocessing.pickle
bins__adj_embs-tuple_tuple_tuple-cosine_similarity-no_postprocessing.pickle
bins__adj_embs-unordered-cosine_similarity-no_postprocessing.pickle
client_id2full_graph_id.pt
client_id2train_graph_id__dict.pt
client_id2train_graph_id.pt
full_graph.bin
gender_graph__05_09_2024.zip
item_id2full_graph_id.pt
item_id2train_graph_id.pt
train_graph.bin
train_graph.gml
train_graph_id2client_id__dict.pt

In [2]:
import dgl

/path/to/repo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
(train_g,), _ = dgl.load_graphs('data/graphs/weighted/train_graph.bin')

In [4]:
(full_g,), _ = dgl.load_graphs('data/graphs/weighted/full_graph.bin')

In [7]:
len(train_g.nodes())

14344

In [9]:
len(train_g.edges()[0])

573328

In [10]:
len(full_g.nodes())

15184

In [11]:
len(full_g.edges()[0])

608214

In [16]:
import numpy as np
from typing import List, Set, Optional

# The original (non-optimized) version
def create_bins_for_user_original(values: List[int], 
                                  n_bins: int, 
                                  exclude_id: Optional[int] = None) -> List[Set[int]]:
    indexed_values = tuple((idx, val) for idx, val in enumerate(values) if idx != exclude_id)

    min_val, max_val = min(indexed_values, key=lambda x: x[1])[1], max(indexed_values, key=lambda x: x[1])[1]
    bin_size = (max_val - min_val) / n_bins
    
    bins = [set() for _ in range(n_bins)]
    
    eps = 1e-6
    for idx, val in indexed_values:
        bin_idx = int((val - min_val) // (bin_size + eps))
        if bin_idx == n_bins:
            bin_idx -= 1
        bins[bin_idx].add(idx)
        
    return bins

# The optimized version
def create_bins_for_user_optimized(values: np.ndarray, 
                                   n_bins: int, 
                                   exclude_id: Optional[int] = None) -> List[Set[int]]:
    if exclude_id is not None:
        mask = np.arange(values.shape[0]) != exclude_id
        indexed_values = np.arange(values.shape[0])[mask]
        values = values[mask]
    else:
        indexed_values = np.arange(values.shape[0])

    min_val, max_val = np.min(values), np.max(values)
    bin_size = (max_val - min_val) / n_bins

    bins = [set() for _ in range(n_bins)]
    
    eps = 1e-6
    bin_indices = np.floor((values - min_val) / (bin_size + eps)).astype(int)
    bin_indices = np.clip(bin_indices, 0, n_bins - 1)
    
    for idx, bin_idx in zip(indexed_values, bin_indices):
        bins[bin_idx].add(idx)
        
    return bins

# Test cases
def test_equal_output():
    # Test case 1: Simple range of values
    values = [1, 2, 3, 4, 5, 6]
    n_bins = 3
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_exclude_id():
    # Test case 2: Exclude an ID
    values = [1, 5, 10, 20]
    n_bins = 2
    exclude_id = 1  # Exclude the element with index 1 (value 5)
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_all_values_same():
    # Test case 3: All values are the same
    values = [10, 10, 10, 10]
    n_bins = 2
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_large_range_of_values():
    # Test case 4: Large range of values
    values = [1, 10, 20, 100, 200, 500, 1000]
    n_bins = 5
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_non_uniform_distribution():
    # Test case 5: Non-uniformly distributed values
    values = [1, 2, 2, 3, 100, 101]
    n_bins = 3
    exclude_id = None
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

def test_exclude_id_out_of_bounds():
    # Test case 6: Exclude an ID that is out of bounds (should do nothing)
    values = [5, 15, 25, 35]
    n_bins = 2
    exclude_id = 10  # Non-existent ID
    
    result_original = create_bins_for_user_original(values, n_bins, exclude_id)
    result_optimized = create_bins_for_user_optimized(np.array(values), n_bins, exclude_id)
    assert result_original == result_optimized

# You can run these tests with pytest by simply running the command:
# pytest <name_of_test_file>.py

In [17]:
test_equal_output()


test_exclude_id()


test_all_values_same()


test_large_range_of_values()


test_non_uniform_distribution()


test_exclude_id_out_of_bounds()

In [16]:
import torch

client_id2train_graph_id = torch.load('./data/graphs/weighted/client_id2train_graph_id.pt')

In [17]:
max(client_id2train_graph_id)

tensor(16000)

In [19]:
# for i in client_id2train_graph_id:
#     print(int(i))